// src/lib/clonechat/intelligence/c1-1/parrain-source-registry.ts
// C1.1 — Registre canonique des sources de connaissance Parrain. Chaque source déclare
// son type, son autorité, sa visibilité, sa portée tenant, sa stratégie de fraîcheur et
// son empreinte. Les registres légers sont dérivés en LIVE (jamais dupliqués à la main) ;
// les scans coûteux (code) passent par un index généré, marqué STALE si la source change.

import { computeCanonicalFingerprints, checkSourceFreshness, type FreshnessCheck } from "./parrain-freshness";
import {
  PARRAIN_SOURCE_TYPES,
  type ParrainSourceEntry,
  type ParrainViewerMode,
} from "./parrain-types";

const AT = "2026-07-10T00:00:00.000Z";
const ALL_MODES: readonly ParrainViewerMode[] = ["public", "client", "founder"];
const CLIENT_UP: readonly ParrainViewerMode[] = ["client", "founder"];
const FOUNDER_ONLY: readonly ParrainViewerMode[] = ["founder"];

export function buildParrainSourceRegistry(): readonly ParrainSourceEntry[] {
  const fp = computeCanonicalFingerprints();
  const e = (x: ParrainSourceEntry): ParrainSourceEntry => Object.freeze(x);
  return Object.freeze([
    e({
      sourceId: "src.route_registry",
      sourceType: "product_registry",
      title: "Registre de routes (nav)",
      sourcePath: "src/lib/nav/route-registry.ts",
      authority: "canonical_registry",
      visibility: "PUBLIC",
      tenantScope: "global",
      freshnessStrategy: "live_derived",
      version: "P9.1",
      contentHash: fp.routeRegistry,
      lastIndexedAt: AT,
      allowedAnswerModes: ALL_MODES,
      citationLabel: "le plan du site",
      canExposeRawContent: false,
      containsSensitiveData: false,
      parser: null,
      fallback: "Orienter vers /questions.",
      status: "active",
    }),
    e({
      sourceId: "src.site_index",
      sourceType: "public_page",
      title: "Index vivant des pages du site",
      sourcePath: "src/lib/clonechat/intelligence/c1/clonechat-site-map.ts + src/app/**/page.tsx",
      authority: "canonical_registry",
      visibility: "PUBLIC",
      tenantScope: "global",
      freshnessStrategy: "live_derived",
      version: "C1.1",
      contentHash: fp.c1SiteMap,
      lastIndexedAt: AT,
      allowedAnswerModes: ALL_MODES,
      citationLabel: "les pages CloneStore",
      canExposeRawContent: false,
      containsSensitiveData: false,
      parser: null,
      fallback: "Donner la page existante la plus proche.",
      status: "active",
    }),
    e({
      sourceId: "src.capability_registry",
      sourceType: "capability_registry",
      title: "Canon des capacités RH de Pierre (P8.10)",
      sourcePath: "src/lib/pierre/v1/hr-canon/capability-registry.ts",
      authority: "canonical_runtime",
      visibility: "PUBLIC",
      tenantScope: "global",
      freshnessStrategy: "live_derived",
      version: `count:${fp.capabilityCount}`,
      contentHash: fp.capabilityRegistry,
      lastIndexedAt: AT,
      allowedAnswerModes: ALL_MODES,
      citationLabel: "les capacités de Pierre",
      canExposeRawContent: false,
      containsSensitiveData: false,
      parser: null,
      fallback: "Décrire le domaine RH sans inventer de capacité.",
      status: "active",
    }),
    e({
      sourceId: "src.t1_registry",
      sourceType: "technology_registry",
      title: "Registre T1 (technologies bas-niveau)",
      sourcePath: "src/lib/clonestore/technologies/t1/technology-registry.ts",
      authority: "canonical_registry",
      visibility: "PUBLIC",
      tenantScope: "global",
      freshnessStrategy: "live_derived",
      version: "T1",
      contentHash: fp.t1Registry,
      lastIndexedAt: AT,
      allowedAnswerModes: ALL_MODES,
      citationLabel: "les technologies CloneStore",
      canExposeRawContent: false,
      containsSensitiveData: false,
      parser: null,
      fallback: "Explication produit générique.",
      status: "active",
    }),
    e({
      sourceId: "src.t2_registry",
      sourceType: "technology_registry",
      title: "Registre T2 (technologies produit)",
      sourcePath: "src/lib/clonestore/product-technologies/t2/product-technology-registry.ts",
      authority: "canonical_registry",
      visibility: "PUBLIC",
      tenantScope: "global",
      freshnessStrategy: "live_derived",
      version: "T2",
      contentHash: fp.t2Registry,
      lastIndexedAt: AT,
      allowedAnswerModes: ALL_MODES,
      citationLabel: "les systèmes CloneStore",
      canExposeRawContent: false,
      containsSensitiveData: false,
      parser: null,
      fallback: "Explication produit générique.",
      status: "active",
    }),
    e({
      sourceId: "src.pricing_resolver",
      sourceType: "pricing_registry",
      title: "Résolveur de prix pays (P10)",
      sourcePath: "src/lib/clonestore/pricing/country-pricing.ts",
      authority: "canonical_runtime",
      visibility: "PUBLIC",
      tenantScope: "global",
      freshnessStrategy: "live_derived",
      version: "P10",
      contentHash: fp.pricing,
      lastIndexedAt: AT,
      allowedAnswerModes: ALL_MODES,
      citationLabel: "la grille tarifaire",
      canExposeRawContent: false,
      containsSensitiveData: false,
      parser: null,
      fallback: "Demander le pays — jamais d'offre par défaut.",
      status: "active",
    }),
    e({
      sourceId: "src.c1_product_truth",
      sourceType: "roadmap_report",
      title: "Vérité produit & roadmap (C1)",
      sourcePath: "src/lib/clonechat/intelligence/c1/clonechat-truth-matrix.ts",
      authority: "verified_report",
      visibility: "PUBLIC",
      tenantScope: "global",
      freshnessStrategy: "live_derived",
      version: "C1",
      contentHash: fp.c1SiteMap,
      lastIndexedAt: AT,
      allowedAnswerModes: ALL_MODES,
      citationLabel: "l'état du produit",
      canExposeRawContent: false,
      containsSensitiveData: false,
      parser: null,
      fallback: "Distinguer disponible / préparé / bloqué.",
      status: "active",
    }),
    e({
      sourceId: "src.readiness_reports",
      sourceType: "readiness_report",
      title: "Rapports de readiness vérifiés (P14/P15/P15.1)",
      sourcePath: "P14/P15/P15.1 reports + production/*.ts",
      authority: "verified_report",
      visibility: "FOUNDER_INTERNAL",
      tenantScope: "global",
      freshnessStrategy: "static_verified",
      version: "P15.1",
      contentHash: "static",
      lastIndexedAt: AT,
      allowedAnswerModes: FOUNDER_ONLY,
      citationLabel: "les rapports internes",
      canExposeRawContent: false,
      containsSensitiveData: false,
      parser: null,
      fallback: "Formulation publique honnête des blocages.",
      status: "active",
    }),
    e({
      sourceId: "src.support_memory",
      sourceType: "support_memory",
      title: "Mémoire support durable (réutilisable vérifié uniquement)",
      sourcePath: "src/lib/clonechat/support-memory.ts + durable/support-store.ts",
      authority: "validated_support",
      visibility: "AUTHENTICATED_CLIENT",
      tenantScope: "company",
      freshnessStrategy: "session_snapshot",
      version: "P9.4.1",
      contentHash: "session",
      lastIndexedAt: AT,
      allowedAnswerModes: CLIENT_UP,
      citationLabel: "les cas support connus",
      canExposeRawContent: false,
      containsSensitiveData: true,
      parser: null,
      fallback: "Créer un cas support tracé.",
      status: "active",
    }),
    e({
      sourceId: "src.bug_memory",
      sourceType: "bug_memory",
      title: "Mémoire de bugs validés (C1)",
      sourcePath: "src/lib/clonechat/intelligence/c1/clonechat-bug-memory.ts",
      authority: "validated_support",
      visibility: "PUBLIC",
      tenantScope: "global",
      freshnessStrategy: "live_derived",
      version: "C1",
      contentHash: "live",
      lastIndexedAt: AT,
      allowedAnswerModes: ALL_MODES,
      citationLabel: "les problèmes connus",
      canExposeRawContent: false,
      containsSensitiveData: false,
      parser: null,
      fallback: "Ne jamais inventer de contournement.",
      status: "active",
    }),
    e({
      sourceId: "src.company_context",
      sourceType: "company_context",
      title: "Contexte entreprise (borné, tenant)",
      sourcePath: "V1 read-only (missions, validations, salariés, documents)",
      authority: "tenant_data",
      visibility: "COMPANY_SCOPED",
      tenantScope: "company",
      freshnessStrategy: "session_snapshot",
      version: "V1",
      contentHash: "session",
      lastIndexedAt: AT,
      allowedAnswerModes: CLIENT_UP,
      citationLabel: "votre espace",
      canExposeRawContent: false,
      containsSensitiveData: true,
      parser: null,
      fallback: "Demander de préciser la mission/le document.",
      status: "active",
    }),
    e({
      sourceId: "src.uploaded_documents",
      sourceType: "uploaded_document",
      title: "Documents téléversés (tenant, session)",
      sourcePath: "pièces jointes de conversation",
      authority: "uploaded_user_content",
      visibility: "COMPANY_SCOPED",
      tenantScope: "company",
      freshnessStrategy: "session_snapshot",
      version: "C1.1",
      contentHash: "session",
      lastIndexedAt: AT,
      allowedAnswerModes: CLIENT_UP,
      citationLabel: "votre document",
      canExposeRawContent: true,
      containsSensitiveData: true,
      parser: "parrain-file-parsers",
      fallback: "Statut honnête (non pris en charge / échec d'extraction).",
      status: "active",
    }),
    e({
      sourceId: "src.generated_documents",
      sourceType: "generated_document",
      title: "Documents générés par Pierre (lineage)",
      sourcePath: "artifacts V1 + trace",
      authority: "tenant_data",
      visibility: "COMPANY_SCOPED",
      tenantScope: "company",
      freshnessStrategy: "session_snapshot",
      version: "V1",
      contentHash: "session",
      lastIndexedAt: AT,
      allowedAnswerModes: CLIENT_UP,
      citationLabel: "le document de Pierre",
      canExposeRawContent: true,
      containsSensitiveData: true,
      parser: null,
      fallback: "Dire quelles preuves manquent — jamais de provenance inventée.",
      status: "active",
    }),
    e({
      sourceId: "src.code_index",
      sourceType: "code_symbol",
      title: "Index code interne (fondateur uniquement)",
      sourcePath: ".c1-1-index/code-index.json (généré par script, allowlist)",
      authority: "canonical_registry",
      visibility: "FOUNDER_INTERNAL",
      tenantScope: "global",
      freshnessStrategy: "generated_index",
      version: "C1.1",
      contentHash: "generated",
      lastIndexedAt: AT,
      allowedAnswerModes: FOUNDER_ONLY,
      citationLabel: "le code interne",
      canExposeRawContent: false,
      containsSensitiveData: false,
      parser: "scripts/clonechat-build-code-index.mjs",
      fallback: "Réponse produit sûre pour les non-internes.",
      status: "active",
    }),
    e({
      sourceId: "src.secrets",
      sourceType: "unknown",
      title: "Matériel secret (env, clés, credentials)",
      sourcePath: ".env* / providers",
      authority: "unverified",
      visibility: "RESTRICTED_SECRET",
      tenantScope: "global",
      freshnessStrategy: "static_verified",
      version: "n/a",
      contentHash: "never",
      lastIndexedAt: AT,
      allowedAnswerModes: [],
      citationLabel: "—",
      canExposeRawContent: false,
      containsSensitiveData: true,
      parser: null,
      fallback: "Jamais indexé, jamais envoyé, jamais cité.",
      status: "blocked",
    }),
  ]);
}

export function sourceById(sourceId: string): ParrainSourceEntry | null {
  return buildParrainSourceRegistry().find((s) => s.sourceId === sourceId) ?? null;
}

/** Contrôle d'intégrité : tout type de source utilisé appartient au vocabulaire fermé. */
export function sourceRegistryValid(): boolean {
  const known = new Set<string>(PARRAIN_SOURCE_TYPES);
  return buildParrainSourceRegistry().every(
    (s) =>
      known.has(s.sourceType) &&
      s.sourceId.length > 0 &&
      s.citationLabel.length > 0 &&
      s.fallback.length > 0 &&
      (s.visibility !== "RESTRICTED_SECRET" || s.allowedAnswerModes.length === 0),
  );
}

/** Fraîcheur par source (le command center et le script de vérification s'appuient dessus). */
export function checkRegistryFreshness(): readonly { sourceId: string; check: FreshnessCheck }[] {
  const fp = computeCanonicalFingerprints();
  return buildParrainSourceRegistry().map((s) => {
    const live =
      s.sourceId === "src.route_registry" ? fp.routeRegistry
      : s.sourceId === "src.capability_registry" ? fp.capabilityRegistry
      : s.sourceId === "src.t1_registry" ? fp.t1Registry
      : s.sourceId === "src.t2_registry" ? fp.t2Registry
      : s.sourceId === "src.pricing_resolver" ? fp.pricing
      : s.sourceId === "src.site_index" || s.sourceId === "src.c1_product_truth" ? fp.c1SiteMap
      : null;
    return { sourceId: s.sourceId, check: checkSourceFreshness(s.freshnessStrategy, s.contentHash, live) };
  });
}
