// B47 — Pierre Document Legal Policy
// Controls legal safety for official HR documents generated by Pierre.
// Pure: no Supabase, no Next, no async. No throw.

import type { LegalRiskLevel } from "../../legal-commercial/types";

export type PierreDocumentType =
  | "attestation"
  | "contract"
  | "contract_amendment"
  | "sanction"
  | "dismissal_letter"
  | "sensitive_hr_letter"
  | "payroll_document"
  | "health_absence_document"
  | "employee_certificate"
  | "onboarding_document"
  | "hr_internal_note"
  | "prepayroll_summary"
  | "general_hr_document";

export type PierreDocumentLegalPolicy = {
  document_type: PierreDocumentType;
  risk_level: LegalRiskLevel;
  human_validation_required: boolean;
  export_allowed_without_validation: boolean;
  auto_send_allowed: boolean;
  required_disclaimers: string[];
  legal_review_recommended: boolean;
  notes: string;
};

const DOCUMENT_POLICIES: Record<PierreDocumentType, PierreDocumentLegalPolicy> = {
  attestation: {
    document_type: "attestation",
    risk_level: "high",
    human_validation_required: true,
    export_allowed_without_validation: false,
    auto_send_allowed: false,
    required_disclaimers: ["OFFICIAL_DOCUMENT_VALIDATION", "HUMAN_RESPONSIBILITY"],
    legal_review_recommended: false,
    notes: "Attestation doit être signée par une personne habilitée avant envoi officiel.",
  },
  contract: {
    document_type: "contract",
    risk_level: "critical",
    human_validation_required: true,
    export_allowed_without_validation: false,
    auto_send_allowed: false,
    required_disclaimers: ["OFFICIAL_DOCUMENT_VALIDATION", "LEGAL_LIMIT", "HUMAN_RESPONSIBILITY"],
    legal_review_recommended: true,
    notes: "Contrat de travail requiert validation humaine et revue juridique recommandée.",
  },
  contract_amendment: {
    document_type: "contract_amendment",
    risk_level: "critical",
    human_validation_required: true,
    export_allowed_without_validation: false,
    auto_send_allowed: false,
    required_disclaimers: ["OFFICIAL_DOCUMENT_VALIDATION", "LEGAL_LIMIT", "HUMAN_RESPONSIBILITY"],
    legal_review_recommended: true,
    notes: "Avenant contractuel requiert validation humaine et revue juridique.",
  },
  sanction: {
    document_type: "sanction",
    risk_level: "critical",
    human_validation_required: true,
    export_allowed_without_validation: false,
    auto_send_allowed: false,
    required_disclaimers: ["OFFICIAL_DOCUMENT_VALIDATION", "LEGAL_LIMIT", "HUMAN_RESPONSIBILITY"],
    legal_review_recommended: true,
    notes: "Courrier de sanction disciplinaire requiert validation RH et revue juridique.",
  },
  dismissal_letter: {
    document_type: "dismissal_letter",
    risk_level: "critical",
    human_validation_required: true,
    export_allowed_without_validation: false,
    auto_send_allowed: false,
    required_disclaimers: ["OFFICIAL_DOCUMENT_VALIDATION", "LEGAL_LIMIT", "HUMAN_RESPONSIBILITY"],
    legal_review_recommended: true,
    notes: "Courrier de licenciement requiert impérativement validation humaine et revue juridique.",
  },
  sensitive_hr_letter: {
    document_type: "sensitive_hr_letter",
    risk_level: "high",
    human_validation_required: true,
    export_allowed_without_validation: false,
    auto_send_allowed: false,
    required_disclaimers: ["OFFICIAL_DOCUMENT_VALIDATION", "HUMAN_RESPONSIBILITY"],
    legal_review_recommended: false,
    notes: "Courrier RH sensible requiert validation humaine avant envoi.",
  },
  payroll_document: {
    document_type: "payroll_document",
    risk_level: "high",
    human_validation_required: true,
    export_allowed_without_validation: false,
    auto_send_allowed: false,
    required_disclaimers: ["PAYROLL_LIMIT", "OFFICIAL_DOCUMENT_VALIDATION"],
    legal_review_recommended: false,
    notes: "Documents de paie préparés par Pierre sont des éléments variables non officiels — validation expert paie requise.",
  },
  health_absence_document: {
    document_type: "health_absence_document",
    risk_level: "high",
    human_validation_required: true,
    export_allowed_without_validation: false,
    auto_send_allowed: false,
    required_disclaimers: ["OFFICIAL_DOCUMENT_VALIDATION", "HUMAN_RESPONSIBILITY"],
    legal_review_recommended: false,
    notes: "Documents relatifs à la santé ou aux absences médicales requièrent validation humaine.",
  },
  employee_certificate: {
    document_type: "employee_certificate",
    risk_level: "high",
    human_validation_required: true,
    export_allowed_without_validation: false,
    auto_send_allowed: false,
    required_disclaimers: ["OFFICIAL_DOCUMENT_VALIDATION"],
    legal_review_recommended: false,
    notes: "Attestation de travail ou certificat doit être signé par personne habilitée.",
  },
  onboarding_document: {
    document_type: "onboarding_document",
    risk_level: "low",
    human_validation_required: false,
    export_allowed_without_validation: true,
    auto_send_allowed: false,
    required_disclaimers: ["AI_LIMIT"],
    legal_review_recommended: false,
    notes: "Documents d'onboarding non officiels peuvent être préparés sans validation, mais vérification recommandée.",
  },
  hr_internal_note: {
    document_type: "hr_internal_note",
    risk_level: "low",
    human_validation_required: false,
    export_allowed_without_validation: true,
    auto_send_allowed: false,
    required_disclaimers: ["AI_LIMIT"],
    legal_review_recommended: false,
    notes: "Note interne RH — usage interne uniquement, pas de valeur légale.",
  },
  prepayroll_summary: {
    document_type: "prepayroll_summary",
    risk_level: "high",
    human_validation_required: true,
    export_allowed_without_validation: false,
    auto_send_allowed: false,
    required_disclaimers: ["PAYROLL_LIMIT", "OFFICIAL_DOCUMENT_VALIDATION"],
    legal_review_recommended: false,
    notes: "Résumé de pré-paie préparatoire — validation expert paie obligatoire avant traitement.",
  },
  general_hr_document: {
    document_type: "general_hr_document",
    risk_level: "low",
    human_validation_required: false,
    export_allowed_without_validation: true,
    auto_send_allowed: false,
    required_disclaimers: ["AI_LIMIT"],
    legal_review_recommended: false,
    notes: "Document RH général — vérification recommandée avant usage officiel.",
  },
};

// ── Functions ─────────────────────────────────────────────────────────────────

export function evaluatePierreDocumentLegalPolicy(documentType: PierreDocumentType): PierreDocumentLegalPolicy {
  return DOCUMENT_POLICIES[documentType] ?? DOCUMENT_POLICIES.general_hr_document;
}

export function requireValidationForDocumentType(documentType: PierreDocumentType): boolean {
  const policy = DOCUMENT_POLICIES[documentType];
  return policy ? policy.human_validation_required : true;
}

export function getOfficialDocumentDisclaimers(documentType: PierreDocumentType): string[] {
  const policy = DOCUMENT_POLICIES[documentType];
  return policy?.required_disclaimers ?? ["OFFICIAL_DOCUMENT_VALIDATION", "HUMAN_RESPONSIBILITY"];
}

export function assertDocumentDoesNotClaimLegalFinality(content: string): { ok: boolean; violations: string[] } {
  const LEGAL_FINALITY_PHRASES = [
    "document légalement valide sans vérification",
    "valeur juridique garantie",
    "conforme sans revue",
    "signé automatiquement",
    "certifié par l'ia",
    "validé juridiquement par pierre",
    "force légale automatique",
  ];
  const lower = content.toLowerCase().normalize("NFD").replace(/[̀-ͯ]/g, "");
  const violations = LEGAL_FINALITY_PHRASES.filter((p) =>
    lower.includes(p.toLowerCase().normalize("NFD").replace(/[̀-ͯ]/g, "")),
  );
  return { ok: violations.length === 0, violations };
}

export function isOfficialDocumentType(documentType: PierreDocumentType): boolean {
  const official: PierreDocumentType[] = [
    "attestation", "contract", "contract_amendment", "sanction",
    "dismissal_letter", "employee_certificate", "payroll_document",
  ];
  return official.includes(documentType);
}

export function getAllDocumentPolicies(): PierreDocumentLegalPolicy[] {
  return Object.values(DOCUMENT_POLICIES);
}
