// P-FINAL 02 — Go-Live Proof Registry
// Canonical list of all proofs required before public launch.
// Pure: no Supabase, no Next, no async, no throw.
// CRITICAL: All proofs default to pending. Never set verified without real evidence.

import type { GoLiveProof } from "./types";

export const GO_LIVE_PROOF_REGISTRY: GoLiveProof[] = [
  // ── LEGAL ─────────────────────────────────────────────────────────────────

  {
    id: "LEGAL_CGU_VALIDATED",
    label: "CGU validées par un conseil juridique",
    category: "legal",
    required_for_public_launch: true,
    required_for_private_pilot: false,
    manual_or_automated: "manual",
    expected_evidence: "Email ou document de validation signé par un juriste avec date",
    verification_steps: [
      "Envoyer les CGU au juriste avec le packet PFINAL02_LEGAL_REVIEW_PACKET.md",
      "Obtenir email/document de validation avec date",
      "Conserver la preuve dans go-live-evidence/",
      "Renseigner le proof ID dans go-live-proofs.local.json",
    ],
    blocking_if_missing: true,
    owner: "gael",
    description: "Les Conditions Générales d'Utilisation ont été relues et approuvées par un avocat ou juriste compétent.",
  },
  {
    id: "LEGAL_CGV_VALIDATED",
    label: "CGV validées par un conseil juridique",
    category: "legal",
    required_for_public_launch: true,
    required_for_private_pilot: false,
    manual_or_automated: "manual",
    expected_evidence: "Email ou document de validation signé par un juriste avec date",
    verification_steps: [
      "Vérifier que les CGV sont sur /legal/cgv sans placeholder",
      "Envoyer au juriste pour validation",
      "Obtenir validation documentée",
    ],
    blocking_if_missing: true,
    owner: "gael",
    description: "Les Conditions Générales de Vente (449€/an, renouvellement, résiliation) ont été validées.",
  },
  {
    id: "LEGAL_DPA_VALIDATED",
    label: "DPA validé par un spécialiste RGPD",
    category: "legal",
    required_for_public_launch: true,
    required_for_private_pilot: false,
    manual_or_automated: "manual",
    expected_evidence: "Validation documentée d'un DPO ou juriste RGPD avec date",
    verification_steps: [
      "Vérifier le DPA sur /legal/dpa",
      "Soumettre à un DPO ou juriste spécialisé RGPD",
      "Obtenir validation écrite",
    ],
    blocking_if_missing: true,
    owner: "gael",
    description: "Le Data Processing Agreement RGPD a été validé par un spécialiste.",
  },
  {
    id: "LEGAL_PRIVACY_VALIDATED",
    label: "Politique de confidentialité validée",
    category: "legal",
    required_for_public_launch: true,
    required_for_private_pilot: false,
    manual_or_automated: "manual",
    expected_evidence: "Validation juridique documentée",
    verification_steps: [
      "Vérifier /legal/confidentialite",
      "Obtenir validation juriste",
    ],
    blocking_if_missing: true,
    owner: "gael",
    description: "La politique de confidentialité est conforme au RGPD et validée.",
  },
  {
    id: "LEGAL_MENTIONS_VALIDATED",
    label: "Mentions légales complétées (aucun placeholder)",
    category: "legal",
    required_for_public_launch: true,
    required_for_private_pilot: true,
    manual_or_automated: "manual",
    expected_evidence: "Vérification manuelle — aucun [placeholder] visible sur /legal/mentions",
    verification_steps: [
      "Ouvrir /legal/mentions dans le navigateur",
      "Vérifier qu'aucun [texte entre crochets] n'est présent",
      "Renseigner: société, SIREN, adresse, hébergeur, DPO",
    ],
    blocking_if_missing: true,
    owner: "gael",
    description: "Toutes les informations réelles de la société ont remplacé les placeholders.",
  },
  {
    id: "LEGAL_ENTITY_INFO_COMPLETED",
    label: "Informations société complétées dans les pages légales",
    category: "legal",
    required_for_public_launch: true,
    required_for_private_pilot: true,
    manual_or_automated: "manual",
    expected_evidence: "SIREN, adresse, capital, hébergeur remplis dans les pages légales",
    verification_steps: [
      "Remplir: nom société, forme juridique, capital",
      "Remplir: SIREN/SIRET, TVA intracommunautaire",
      "Remplir: adresse siège social",
      "Remplir: hébergeur (Vercel/Railway) avec adresse",
      "Remplir: DPO ou contact RGPD",
    ],
    blocking_if_missing: true,
    owner: "gael",
    description: "Toutes les données de la société éditrice sont renseignées dans les pages légales.",
  },
  {
    id: "LEGAL_HUMAN_REVIEW_COMPLETED",
    label: "Revue juridique humaine globale effectuée",
    category: "legal",
    required_for_public_launch: true,
    required_for_private_pilot: false,
    manual_or_automated: "manual",
    expected_evidence: "Email ou compte-rendu de revue juridique globale (claims, responsabilité, B47)",
    verification_steps: [
      "Envoyer PFINAL02_LEGAL_REVIEW_PACKET.md au juriste",
      "Faire valider les claims autorisées/interdites de Pierre",
      "Faire valider les limitations de responsabilité",
      "Obtenir avis écrit",
    ],
    blocking_if_missing: true,
    owner: "lawyer",
    description: "Un juriste a relu les guardrails B47, les promesses commerciales et les limites de responsabilité.",
  },

  // ── SUPABASE / SÉCURITÉ ────────────────────────────────────────────────────

  {
    id: "SUPABASE_RLS_STAGING_APPLIED",
    label: "RLS appliqué sur staging Supabase",
    category: "supabase",
    required_for_public_launch: true,
    required_for_private_pilot: true,
    manual_or_automated: "manual",
    expected_evidence: "Screenshot de pg_policies sur staging montrant les 23 politiques",
    verification_steps: [
      "Ouvrir SQL Editor Supabase STAGING",
      "Coller et exécuter PFINAL01_RLS_PRODUCTION_PACK.sql",
      "Vérifier: SELECT COUNT(*) FROM pg_policies WHERE schemaname='public' → 23+",
      "Screenshot et enregistrer dans go-live-evidence/",
    ],
    blocking_if_missing: true,
    owner: "developer",
    description: "Le SQL pack RLS a été appliqué sur l'environnement staging.",
  },
  {
    id: "SUPABASE_RLS_STAGING_VERIFIED",
    label: "RLS staging vérifié — isolation testée",
    category: "supabase",
    required_for_public_launch: true,
    required_for_private_pilot: true,
    manual_or_automated: "manual",
    expected_evidence: "Résultat de test cross-company sur staging: 0 rows cross-company",
    verification_steps: [
      "Créer user A (company A) et user B (company B) sur staging",
      "Connecté en user A: SELECT * FROM employees → 0 rows de company B",
      "Connecté en user B: SELECT * FROM employees → 0 rows de company A",
      "Documenter le résultat",
    ],
    blocking_if_missing: true,
    owner: "developer",
    description: "L'isolation RLS a été validée sur staging: aucun accès cross-company.",
  },
  {
    id: "SUPABASE_RLS_PRODUCTION_APPLIED",
    label: "RLS appliqué sur production Supabase",
    category: "supabase",
    required_for_public_launch: true,
    required_for_private_pilot: false,
    manual_or_automated: "manual",
    expected_evidence: "Screenshot de pg_policies sur production montrant les 23 politiques",
    verification_steps: [
      "Prendre un backup production d'abord",
      "Appliquer PFINAL01_RLS_PRODUCTION_PACK.sql dans une transaction",
      "Vérifier pg_policies post-application",
      "Screenshot production policies",
    ],
    blocking_if_missing: true,
    owner: "developer",
    description: "Le SQL pack RLS a été appliqué sur l'environnement production.",
  },
  {
    id: "SUPABASE_RLS_PRODUCTION_VERIFIED",
    label: "RLS production vérifié — accès anon bloqué",
    category: "supabase",
    required_for_public_launch: true,
    required_for_private_pilot: false,
    manual_or_automated: "manual",
    expected_evidence: "Test production: clé anon → 0 rows sur employees, documents, tasks",
    verification_steps: [
      "Avec clé anon: SELECT * FROM employees → doit retourner 0 rows",
      "Avec clé anon: SELECT * FROM documents → doit retourner 0 rows",
      "Documenter le résultat",
    ],
    blocking_if_missing: true,
    owner: "developer",
    description: "La clé anon Supabase ne peut lire aucune donnée sensible en production.",
  },
  {
    id: "SUPABASE_USER_A_CANNOT_READ_USER_B",
    label: "Isolation cross-company vérifiée en production",
    category: "supabase",
    required_for_public_launch: true,
    required_for_private_pilot: false,
    manual_or_automated: "manual",
    expected_evidence: "Test production: user A ne peut pas lire les données de user B",
    verification_steps: [
      "Créer 2 comptes de test production appartenant à 2 companies distinctes",
      "Vérifier que SELECT * FROM employees filtre par company_id",
      "0 rows cross-company attendu",
    ],
    blocking_if_missing: true,
    owner: "developer",
    description: "Un utilisateur ne peut pas accéder aux données d'une autre entreprise.",
  },
  {
    id: "SUPABASE_SERVICE_ROLE_ROUTES_VERIFIED",
    label: "Routes service_role vérifiées (audit_logs, ai_cost_events)",
    category: "supabase",
    required_for_public_launch: true,
    required_for_private_pilot: false,
    manual_or_automated: "manual",
    expected_evidence: "Test: INSERT audit_logs avec clé anon → erreur RLS. INSERT avec service_role → succès.",
    verification_steps: [
      "Tester INSERT audit_logs avec clé anon → doit échouer (RLS)",
      "Tester INSERT ai_cost_events avec clé anon → doit échouer",
      "Vérifier que SUPABASE_SERVICE_ROLE_KEY est utilisée uniquement côté serveur",
    ],
    blocking_if_missing: true,
    owner: "developer",
    description: "Les tables d'audit et de coûts IA ne sont accessibles qu'en service_role.",
  },

  // ── STRIPE ─────────────────────────────────────────────────────────────────

  {
    id: "STRIPE_LIVE_SECRET_SET",
    label: "Clé secrète Stripe live configurée (sk_live_...)",
    category: "stripe",
    required_for_public_launch: true,
    required_for_private_pilot: false,
    manual_or_automated: "automated",
    expected_evidence: "Script pfinal02-stripe-live-verify.ps1 confirme sk_live_ prefix détecté",
    verification_steps: [
      "Dashboard Stripe → Developers → API keys → Live mode",
      "Copier la Secret key (sk_live_...)",
      "Setter STRIPE_SECRET_KEY=sk_live_... dans les variables d'env production",
      "Lancer npm run check:stripe-live pour vérification",
    ],
    blocking_if_missing: true,
    owner: "gael",
    description: "La clé secrète Stripe live est configurée en production.",
  },
  {
    id: "STRIPE_LIVE_PRICE_PIERRE_449_CREATED",
    label: "Prix Stripe live Pierre 449€/an créé",
    category: "stripe",
    required_for_public_launch: true,
    required_for_private_pilot: false,
    manual_or_automated: "manual",
    expected_evidence: "Price ID (price_live_...) visible dans Dashboard Stripe → Products",
    verification_steps: [
      "Dashboard Stripe → Products → Add product",
      "Nom: Pierre — Assistant RH Annual, Prix: 449€ EUR, récurrence: annuel",
      "Copier le Price ID",
      "Setter STRIPE_PIERRE_ANNUAL_PRICE_ID=price_... en production",
    ],
    blocking_if_missing: true,
    owner: "gael",
    description: "Le produit Pierre et le prix live 449€/an sont créés dans Stripe.",
  },
  {
    id: "STRIPE_LIVE_WEBHOOK_CONFIGURED",
    label: "Webhook Stripe live configuré",
    category: "stripe",
    required_for_public_launch: true,
    required_for_private_pilot: false,
    manual_or_automated: "manual",
    expected_evidence: "Screenshot Dashboard Stripe → Webhooks avec endpoint actif et statut ✓",
    verification_steps: [
      "Dashboard Stripe → Developers → Webhooks → Add endpoint",
      "URL: https://[domaine]/api/webhooks/stripe",
      "Events: checkout.session.completed, customer.subscription.created/updated/deleted, invoice.paid, invoice.payment_failed, charge.refunded, charge.dispute.created/closed",
      "Copier webhook secret (whsec_...)",
      "Setter STRIPE_WEBHOOK_SECRET=whsec_... en production",
    ],
    blocking_if_missing: true,
    owner: "gael",
    description: "L'endpoint webhook Stripe est configuré et actif en production.",
  },
  {
    id: "STRIPE_LIVE_CHECKOUT_TESTED",
    label: "Checkout Stripe live testé (page vérifiée)",
    category: "stripe",
    required_for_public_launch: true,
    required_for_private_pilot: false,
    manual_or_automated: "manual",
    expected_evidence: "Screenshot de la page Stripe Checkout avec montant 449€ visible",
    verification_steps: [
      "Aller sur /checkout?agent=pierre en production",
      "Vérifier que la page Stripe s'ouvre avec 449€",
      "Ne pas finaliser le paiement pour ce test (arrêter avant la carte)",
      "Screenshot de la page Checkout",
    ],
    blocking_if_missing: true,
    owner: "gael",
    description: "La page checkout Stripe live s'ouvre correctement avec le bon montant.",
  },
  {
    id: "STRIPE_LIVE_PAYMENT_SUCCESS_TESTED",
    label: "Paiement Stripe live success testé de bout en bout",
    category: "stripe",
    required_for_public_launch: true,
    required_for_private_pilot: false,
    manual_or_automated: "manual",
    expected_evidence: "Screenshot success page + order en DB + accès Pierre activé",
    verification_steps: [
      "Créer compte de test production",
      "Faire le checkout complet avec vraie carte (ou Stripe test clock)",
      "Vérifier success page → accès Pierre activé",
      "Vérifier en DB: orders.status = active",
      "Vérifier webhook delivery dans Dashboard Stripe",
    ],
    blocking_if_missing: true,
    owner: "gael",
    description: "Le flux complet paiement → activation Pierre fonctionne en production.",
  },
  {
    id: "STRIPE_LIVE_PAYMENT_FAILURE_TESTED",
    label: "Paiement Stripe live échec géré proprement",
    category: "stripe",
    required_for_public_launch: false,
    required_for_private_pilot: false,
    manual_or_automated: "manual",
    expected_evidence: "Comportement de l'app documenté en cas d'échec de paiement",
    verification_steps: [
      "Utiliser carte de test Stripe pour simuler un refus (4000000000000002)",
      "Vérifier que l'app affiche un message d'erreur clair",
      "Vérifier que Pierre n'est PAS activé",
    ],
    blocking_if_missing: false,
    owner: "gael",
    description: "Les paiements Stripe échoués sont gérés proprement sans activer Pierre.",
  },
  {
    id: "STRIPE_LIVE_SUBSCRIPTION_CANCEL_TESTED",
    label: "Annulation abonnement Stripe testée",
    category: "stripe",
    required_for_public_launch: false,
    required_for_private_pilot: false,
    manual_or_automated: "manual",
    expected_evidence: "Comportement de l'app documenté en cas d'annulation subscription",
    verification_steps: [
      "Annuler l'abonnement via Dashboard Stripe ou via l'app",
      "Vérifier webhook subscription.deleted reçu",
      "Vérifier que l'accès Pierre est révoqué",
    ],
    blocking_if_missing: false,
    owner: "gael",
    description: "L'annulation Stripe révoque correctement l'accès Pierre.",
  },

  // ── EMAIL / DOMAINE ────────────────────────────────────────────────────────

  {
    id: "EMAIL_DOMAIN_VERIFIED",
    label: "Domaine email vérifié sur Resend",
    category: "email",
    required_for_public_launch: false,
    required_for_private_pilot: false,
    manual_or_automated: "manual",
    expected_evidence: "Screenshot Dashboard Resend avec domaine statut Verified",
    verification_steps: [
      "Dashboard Resend → Domains → Add domain",
      "Ajouter les enregistrements DNS requis",
      "Attendre vérification (peut prendre 24h)",
    ],
    blocking_if_missing: false,
    owner: "gael",
    description: "Le domaine d'envoi email est vérifié sur Resend.",
  },
  {
    id: "EMAIL_FROM_ADDRESS_VERIFIED",
    label: "Adresse 'from' email professionnelle configurée",
    category: "email",
    required_for_public_launch: false,
    required_for_private_pilot: false,
    manual_or_automated: "manual",
    expected_evidence: "RESEND_DEFAULT_FROM configuré avec adresse professionnelle",
    verification_steps: [
      "Configurer RESEND_DEFAULT_FROM=Pierre <pierre@[votre-domaine]>",
      "Tester en sandbox mode",
    ],
    blocking_if_missing: false,
    owner: "gael",
    description: "L'adresse d'expéditeur Pierre est professionnelle et configurée.",
  },
  {
    id: "EMAIL_SANDBOX_SEND_TESTED",
    label: "Envoi email sandbox testé (pas de live)",
    category: "email",
    required_for_public_launch: false,
    required_for_private_pilot: false,
    manual_or_automated: "manual",
    expected_evidence: "Résultat test envoi sandbox dans logs ou Dashboard Resend",
    verification_steps: [
      "Configurer EMAIL_RUNTIME_MODE=sandbox",
      "Configurer EMAIL_SANDBOX_TO=votre-email-test",
      "Déclencher un envoi test",
      "Vérifier réception sur la boîte sandbox",
    ],
    blocking_if_missing: false,
    owner: "gael",
    description: "Les emails en mode sandbox arrivent correctement.",
  },
  {
    id: "EMAIL_SENSITIVE_SEND_BLOCKED_VERIFIED",
    label: "Blocage email sensible vérifié en production",
    category: "email",
    required_for_public_launch: true,
    required_for_private_pilot: true,
    manual_or_automated: "automated",
    expected_evidence: "Test: email.send avec cas sensible → bloqué par pierre-email-policy",
    verification_steps: [
      "Créer une mission avec contenu de licenciement",
      "Vérifier que Pierre produit un brouillon (jamais un envoi direct)",
      "Vérifier que le brouillon nécessite validation humaine",
    ],
    blocking_if_missing: true,
    owner: "developer",
    description: "Les emails sensibles (licenciement, sanctions) sont bloqués à l'envoi auto.",
  },

  // ── DEMO ───────────────────────────────────────────────────────────────────

  {
    id: "DEMO_PUBLIC_SAFE_VERIFIED",
    label: "Page /demo/pierre vérifiée safe pour le public",
    category: "demo",
    required_for_public_launch: true,
    required_for_private_pilot: true,
    manual_or_automated: "hybrid",
    expected_evidence: "Test npm run test:pfinal01-demo passé + vérification manuelle de la page",
    verification_steps: [
      "Lancer npm run test:pfinal01-demo",
      "Ouvrir /demo/pierre dans le navigateur sans être connecté",
      "Vérifier bannière orange DÉMO visible",
      "Vérifier aucun appel API externe dans l'onglet Réseau",
    ],
    blocking_if_missing: true,
    owner: "developer",
    description: "La démo publique est safe: aucune IA réelle, aucun email, aucun compte.",
  },
  {
    id: "DEMO_NO_REAL_AI_VERIFIED",
    label: "Démo: aucun appel IA réel possible",
    category: "demo",
    required_for_public_launch: true,
    required_for_private_pilot: true,
    manual_or_automated: "automated",
    expected_evidence: "Test unitaire DemoSession.ai_calls_allowed === false",
    verification_steps: [
      "Vérifier createDemoSession().ai_calls_allowed === false",
      "Vérifier guardDemoOperation('ai_api_call').allowed === false",
    ],
    blocking_if_missing: true,
    owner: "developer",
    description: "La session démo bloque systématiquement tous les appels IA.",
  },
  {
    id: "DEMO_NO_REAL_EMAIL_VERIFIED",
    label: "Démo: aucun email réel possible",
    category: "demo",
    required_for_public_launch: true,
    required_for_private_pilot: true,
    manual_or_automated: "automated",
    expected_evidence: "Test unitaire DemoSession.email_send_allowed === false",
    verification_steps: [
      "Vérifier createDemoSession().email_send_allowed === false",
      "Vérifier guardDemoOperation('email_send').allowed === false",
    ],
    blocking_if_missing: true,
    owner: "developer",
    description: "La session démo bloque systématiquement tout envoi d'email.",
  },
  {
    id: "DEMO_NO_REAL_ACTION_VERIFIED",
    label: "Démo: aucune action réelle possible (Stripe, DB write)",
    category: "demo",
    required_for_public_launch: true,
    required_for_private_pilot: true,
    manual_or_automated: "automated",
    expected_evidence: "Test: guardDemoOperation pour stripe_checkout et database_write → bloqué",
    verification_steps: [
      "Vérifier guardDemoOperation('stripe_checkout').allowed === false",
      "Vérifier guardDemoOperation('database_write').allowed === false",
    ],
    blocking_if_missing: true,
    owner: "developer",
    description: "Aucune action réelle (paiement, écriture DB) n'est possible en démo.",
  },

  // ── PAID CUSTOMER ──────────────────────────────────────────────────────────

  {
    id: "PAID_CUSTOMER_PRODUCTION_E2E_VERIFIED",
    label: "Flow paid customer production testé de bout en bout",
    category: "paid_customer",
    required_for_public_launch: true,
    required_for_private_pilot: false,
    manual_or_automated: "manual",
    expected_evidence: "Checklist pfinal02-paid-customer-production-checklist.ps1 complétée",
    verification_steps: [
      "Créer compte test production",
      "Payer l'abonnement (vraie carte ou test clock)",
      "Vérifier activation Pierre",
      "Créer mission simple",
      "Vérifier brouillon document",
      "Vérifier blocage cas sensible",
    ],
    blocking_if_missing: true,
    owner: "gael",
    description: "Le parcours complet d'un client payant a été testé en production.",
  },
  {
    id: "PIERRE_ACCESS_AFTER_PAYMENT_VERIFIED",
    label: "Accès Pierre activé après paiement production",
    category: "paid_customer",
    required_for_public_launch: true,
    required_for_private_pilot: false,
    manual_or_automated: "manual",
    expected_evidence: "Accès /agents/pierre/use confirmé après paiement production réel",
    verification_steps: [
      "Après paiement test réussi",
      "Vérifier que /agents/pierre/use est accessible",
      "Vérifier que le cockpit charge les données de la company",
    ],
    blocking_if_missing: true,
    owner: "gael",
    description: "Un client ayant payé peut accéder à Pierre en production.",
  },
  {
    id: "PIERRE_BLOCK_AFTER_CANCEL_VERIFIED",
    label: "Accès Pierre bloqué après annulation abonnement",
    category: "paid_customer",
    required_for_public_launch: false,
    required_for_private_pilot: false,
    manual_or_automated: "manual",
    expected_evidence: "Test: annulation abonnement → /agents/pierre/use redirige vers /checkout",
    verification_steps: [
      "Annuler l'abonnement test via Dashboard Stripe",
      "Vérifier que l'accès Pierre est révoqué",
      "Vérifier redirection vers /checkout",
    ],
    blocking_if_missing: false,
    owner: "gael",
    description: "Un client ayant annulé perd l'accès Pierre.",
  },

  // ── PUBLIC COPY ────────────────────────────────────────────────────────────

  {
    id: "PUBLIC_COPY_SCAN_CLEAN",
    label: "Scan contenu public passé sans violations bloquantes",
    category: "copy",
    required_for_public_launch: true,
    required_for_private_pilot: true,
    manual_or_automated: "automated",
    expected_evidence: "npm run test:pfinal01-copy passé + scan manuel homepage/pricing/demo",
    verification_steps: [
      "Lancer npm run test:pfinal01-copy",
      "Lancer npm run check:go-live",
      "Vérifier résultat: aucune violation bloquante",
    ],
    blocking_if_missing: true,
    owner: "developer",
    description: "Aucune formulation interdite sur les pages publiques homepage/pricing/demo.",
  },
  {
    id: "PUBLIC_SITE_NO_FORBIDDEN_CLAIMS",
    label: "Pages publiques sans claims interdites Pierre",
    category: "copy",
    required_for_public_launch: true,
    required_for_private_pilot: true,
    manual_or_automated: "hybrid",
    expected_evidence: "Scan copy-scanner + vérification manuelle des pages publiques",
    verification_steps: [
      "Vérifier aucune occurrence de 'Pierre garantit'",
      "Vérifier aucune occurrence de 'remplace avocat'",
      "Vérifier aucune occurrence de 'zéro erreur'",
      "Vérifier aucun 'essai gratuit de 7 jours'",
    ],
    blocking_if_missing: true,
    owner: "developer",
    description: "Aucune page publique ne contient de claims prohibées sur Pierre.",
  },
  {
    id: "CHECKOUT_LEGAL_LINKS_PRESENT",
    label: "Liens légaux présents sur la page checkout",
    category: "copy",
    required_for_public_launch: true,
    required_for_private_pilot: false,
    manual_or_automated: "manual",
    expected_evidence: "Vérification manuelle: liens CGU et politique de confidentialité visibles sur /checkout",
    verification_steps: [
      "Ouvrir /checkout dans le navigateur",
      "Vérifier que liens CGU sont présents",
      "Vérifier que lien politique confidentialité est présent",
      "Vérifier que les liens fonctionnent",
    ],
    blocking_if_missing: true,
    owner: "gael",
    description: "La page checkout affiche les liens légaux obligatoires.",
  },

  // ── BUILD / TECH ───────────────────────────────────────────────────────────

  {
    id: "FINAL_BUILD_CLEAN",
    label: "Build production propre (npm run build)",
    category: "build",
    required_for_public_launch: true,
    required_for_private_pilot: true,
    manual_or_automated: "automated",
    expected_evidence: "Résultat npm run build: aucune erreur, aucun warning TypeScript",
    verification_steps: [
      "Lancer npx tsc --noEmit → 0 erreurs",
      "Lancer npm run build → succès",
      "Vérifier aucune erreur dans la sortie build",
    ],
    blocking_if_missing: true,
    owner: "developer",
    description: "Le build Next.js production est propre sans erreur.",
  },
  {
    id: "FINAL_TESTS_CLEAN",
    label: "Tous les tests passent (npm test)",
    category: "build",
    required_for_public_launch: true,
    required_for_private_pilot: true,
    manual_or_automated: "automated",
    expected_evidence: "npm test: 7000+ tests passing, 0 failing",
    verification_steps: [
      "Lancer npm test",
      "Vérifier 0 test en échec",
      "Lancer npm run test:pfinal01",
      "Lancer npm run test:pfinal02",
    ],
    blocking_if_missing: true,
    owner: "developer",
    description: "L'intégralité de la suite de tests passe sans erreur.",
  },
];

// ── Registry functions ────────────────────────────────────────────────────────

export function getGoLiveProofRegistry(): GoLiveProof[] {
  return [...GO_LIVE_PROOF_REGISTRY];
}

export function getRequiredPublicLaunchProofs(): GoLiveProof[] {
  return GO_LIVE_PROOF_REGISTRY.filter((p) => p.required_for_public_launch);
}

export function getRequiredPrivatePilotProofs(): GoLiveProof[] {
  return GO_LIVE_PROOF_REGISTRY.filter((p) => p.required_for_private_pilot);
}

export function getProofsByCategory(category: string): GoLiveProof[] {
  return GO_LIVE_PROOF_REGISTRY.filter((p) => p.category === category);
}

export function getBlockingProofs(): GoLiveProof[] {
  return GO_LIVE_PROOF_REGISTRY.filter((p) => p.blocking_if_missing);
}

export function getProofById(id: string): GoLiveProof | undefined {
  return GO_LIVE_PROOF_REGISTRY.find((p) => p.id === id);
}
