// src/lib/pierre/v1/hr-canon/capability-registry.ts
// PHASE 8.10 — THE registry: every atomic HR capability Pierre must know/decide/prepare/execute/
// monitor/prove, with an honest implementation status grounded in the P8.10 read-only audit of
// the real codebase (.p810-proofs + scripts/p810-verify-hr-canon.mjs). Each entry is a concise
// seed; defineCapability() fills the full contract. VERIFIED_EXISTING entries carry real evidence
// (module/route/test/prior-P8 proof); everything else is honestly MISSING / PARTIAL / CONTRACT_ONLY
// / EXTERNAL_DEPENDENCY / LEGAL_CONTENT_REQUIRED / HUMAN_ONLY and routed to P8.11 or P8.12.
//
// Status honesty rule: file existence is NOT proof. VERIFIED_EXISTING is used only where the audit
// cited a concrete test / route+mutation / DB state-machine / migration table / prior P8 proof.

import type { HrCapabilitySeed, HrCapabilityDefinition, HrRiskClassification, HrEvidenceReference, HrImplementationReference } from "./types";
import { defineCapability } from "./capability-schema";

// ── compact authoring helpers ────────────────────────────────────────────────
const risk = (level: HrRiskClassification["level"], o: Partial<HrRiskClassification> = {}): HrRiskClassification => ({
  level, reversibility: o.reversibility ?? "reversible", legalSensitivity: o.legalSensitivity ?? "standard",
  dataSensitivity: o.dataSensitivity ?? "normal", reasons: o.reasons ?? [],
});
const mod = (path: string, symbol?: string): HrImplementationReference => ({ kind: "module", path, symbol });
const route = (path: string): HrImplementationReference => ({ kind: "route", path });
const ev = (kind: HrEvidenceReference["kind"], ref: string, proves: string): HrEvidenceReference => ({ kind, ref, proves });

const RAW: HrCapabilitySeed[] = [
  // ══ A. ORGANISATION & PLANNING ═════════════════════════════════════════════
  { id: "org.read_company", domain: "org", operation: "read_company", label: "Read company information", lifecycleStages: ["daily_admin"], autonomy: "execute_autonomous", implementation: "VERIFIED_EXISTING", risk: risk("low"), implementationReferences: [mod("src/lib/pierre/v1/company.ts", "getCompany"), route("src/app/api/pierre/v1/company/route.ts")], evidence: [ev("integration_test", "p82c-route-security.itest.ts", "governed viewer read")] },
  { id: "org.update_company", domain: "org", operation: "update_company", label: "Update company properties", lifecycleStages: ["daily_admin"], autonomy: "execute_with_validation", implementation: "VERIFIED_EXISTING", risk: risk("medium"), implementationReferences: [mod("src/lib/pierre/v1/company.ts", "patchCompany")], evidence: [ev("integration_test", "p82c-operational.itest.ts", "governed update + version conflict")] },
  { id: "org.create_site", domain: "org", operation: "create_site", label: "Create establishment/site", lifecycleStages: ["daily_admin"], autonomy: "execute_with_validation", implementation: "VERIFIED_EXISTING", risk: risk("medium"), implementationReferences: [mod("src/lib/pierre/v1/sites.ts", "createSite")], evidence: [ev("integration_test", "p82c-operational.itest.ts", "site.write governed create")] },
  { id: "org.update_site", domain: "org", operation: "update_site", label: "Update site properties", lifecycleStages: ["daily_admin"], autonomy: "execute_with_validation", implementation: "VERIFIED_EXISTING", risk: risk("low"), implementationReferences: [mod("src/lib/pierre/v1/sites.ts", "patchSite")], evidence: [ev("integration_test", "p82c-operational.itest.ts", "optimistic versioning")] },
  { id: "org.archive_site", domain: "org", operation: "archive_site", label: "Archive site + reassign employees", lifecycleStages: ["daily_admin"], autonomy: "execute_with_validation", implementation: "VERIFIED_EXISTING", risk: risk("medium", { reversibility: "partially_reversible" }), implementationReferences: [mod("src/lib/pierre/v1/sites.ts", "archiveSite")], evidence: [ev("integration_test", "p82c-operational.itest.ts", "atomic reassignment, blocks with active employees")] },
  { id: "org.assign_site_manager", domain: "org", operation: "assign_site_manager", label: "Assign site manager", lifecycleStages: ["daily_admin"], autonomy: "execute_with_validation", implementation: "VERIFIED_EXISTING", risk: risk("medium"), implementationReferences: [mod("src/lib/pierre/v1/sites.ts", "assignSiteManager")], evidence: [ev("integration_test", "p82c-operational.itest.ts", "validates active member + site scope")] },
  { id: "org.list_sites", domain: "org", operation: "list_sites", label: "List sites (RBAC-scoped)", lifecycleStages: ["daily_admin"], autonomy: "execute_autonomous", implementation: "VERIFIED_EXISTING", risk: risk("low"), implementationReferences: [mod("src/lib/pierre/v1/sites.ts", "listSites")], evidence: [ev("integration_test", "tenancy-rbac-employee360.itest.ts", "site-scope filtering")] },
  { id: "org.manage_org_structure", domain: "org", operation: "manage_org_structure", label: "Model teams/departments/positions & org chart", lifecycleStages: ["daily_admin", "reporting"], autonomy: "prepare_draft", implementation: "PARTIAL", risk: risk("low"), implementationReferences: [mod("src/lib/pierre/v1/sites.ts"), mod("src/lib/pierre/v1/members.ts")], evidence: [] },
  { id: "org.workforce_planning", domain: "org", operation: "workforce_planning", label: "Workforce planning, headcount & future needs", lifecycleStages: ["reporting", "pre_hire"], autonomy: "suggest", implementation: "MISSING", risk: risk("low") },
  { id: "org.position_budget", domain: "org", operation: "position_budget", label: "Position budgeting & approval", lifecycleStages: ["pre_hire"], autonomy: "prepare_draft", implementation: "MISSING", risk: risk("medium") },
  { id: "org.succession_planning", domain: "org", operation: "succession_planning", label: "Succession planning for key roles", lifecycleStages: ["reporting", "career"], autonomy: "suggest", implementation: "MISSING", risk: risk("medium", { dataSensitivity: "sensitive" }) },
  { id: "org.restructuring_prepare", domain: "org", operation: "restructuring_prepare", label: "Prepare restructuring scenarios (analysis only)", lifecycleStages: ["reporting"], autonomy: "observe_only", implementation: "MISSING", risk: risk("high", { legalSensitivity: "high", reasons: ["collective procedures are legally sensitive"] }), countryRuleDependencies: [{ ruleFamily: "employee_representation", required: true }] },

  // ══ B. RECRUITMENT ═════════════════════════════════════════════════════════
  { id: "recruitment.classify_intent", domain: "recruitment", operation: "classify_intent", label: "Detect recruitment intent from request", lifecycleStages: ["recruitment"], autonomy: "execute_autonomous", implementation: "IMPLEMENTED_UNVERIFIED", risk: risk("low"), implementationReferences: [mod("src/lib/pierre/mission/classify.ts")], evidence: [] },
  { id: "recruitment.plan_hiring_tasks", domain: "recruitment", operation: "plan_hiring_tasks", label: "Plan hiring tasks & missing-info detection", lifecycleStages: ["recruitment"], autonomy: "prepare_draft", implementation: "VERIFIED_EXISTING", risk: risk("low"), implementationReferences: [mod("src/lib/pierre/hr/workflows.ts")], evidence: [ev("unit_test", "hr-workflows.test.ts", "hiring task planning + missing-info detection")] },
  { id: "recruitment.job_requisition", domain: "recruitment", operation: "job_requisition", label: "Open a job requisition (need, job description, budget approval)", lifecycleStages: ["pre_hire", "recruitment"], autonomy: "prepare_draft", implementation: "MISSING", risk: risk("medium") },
  { id: "recruitment.posting", domain: "recruitment", operation: "posting", label: "Publish/post an opening", lifecycleStages: ["recruitment"], autonomy: "prepare_draft", implementation: "MISSING", risk: risk("low") },
  { id: "recruitment.sourcing", domain: "recruitment", operation: "sourcing", label: "Sourcing & candidate intake", lifecycleStages: ["recruitment"], autonomy: "suggest", implementation: "MISSING", risk: risk("medium", { dataSensitivity: "sensitive" }) },
  { id: "recruitment.pipeline", domain: "recruitment", operation: "pipeline", label: "Candidate pipeline & talent pool management", lifecycleStages: ["recruitment"], autonomy: "prepare_draft", implementation: "MISSING", risk: risk("medium", { dataSensitivity: "sensitive" }) },
  { id: "recruitment.interview_scheduling", domain: "recruitment", operation: "interview_scheduling", label: "Interview scheduling & evaluation capture", lifecycleStages: ["recruitment"], autonomy: "prepare_draft", implementation: "PARTIAL", risk: risk("medium") },
  { id: "recruitment.reference_checks", domain: "recruitment", operation: "reference_checks", label: "Reference checks", lifecycleStages: ["recruitment"], autonomy: "prepare_draft", implementation: "MISSING", risk: risk("medium", { dataSensitivity: "sensitive" }) },
  { id: "recruitment.screening_decision", domain: "recruitment", operation: "screening_decision", label: "Screening/hiring decision (accept/reject)", lifecycleStages: ["recruitment"], autonomy: "execute_with_validation", implementation: "PARTIAL", risk: risk("high", { legalSensitivity: "high", reasons: ["non-discrimination"] }) },
  { id: "recruitment.candidate_rejection", domain: "recruitment", operation: "candidate_rejection", label: "Formal candidate rejection notification", lifecycleStages: ["recruitment"], autonomy: "prepare_draft", implementation: "IMPLEMENTED_UNVERIFIED", risk: risk("medium", { legalSensitivity: "high" }), implementationReferences: [mod("src/lib/pierre/hr/contracts.ts"), mod("src/lib/pierre/hr/workflows.ts")], evidence: [] },
  { id: "recruitment.candidate_data_compliance", domain: "recruitment", operation: "candidate_data_compliance", label: "Candidate data GDPR/consent & retention", lifecycleStages: ["recruitment", "compliance"], autonomy: "prepare_draft", implementation: "MISSING", risk: risk("high", { dataSensitivity: "sensitive", legalSensitivity: "high" }), countryRuleDependencies: [{ ruleFamily: "data_protection", required: true }] },

  // ══ C. OFFER & PRE-HIRE ════════════════════════════════════════════════════
  { id: "offer.generate_offer_document", domain: "offer", operation: "generate_offer_document", label: "Generate job-offer document (promesse d'embauche)", lifecycleStages: ["hiring"], autonomy: "prepare_draft", implementation: "CONTRACT_ONLY", risk: risk("high", { legalSensitivity: "high", reasons: ["binding pre-contractual commitment"] }), implementationReferences: [mod("src/lib/pierre/v1/document-types.ts")], countryRuleDependencies: [{ ruleFamily: "contract_types", required: true }] },
  { id: "offer.render_offer_premium", domain: "offer", operation: "render_offer_premium", label: "Render offer document (premium)", lifecycleStages: ["hiring"], autonomy: "execute_autonomous", implementation: "VERIFIED_EXISTING", risk: risk("low"), implementationReferences: [mod("src/lib/pierre/documents/premium-documents.ts"), mod("src/lib/pierre/v1/renderers.ts")], evidence: [ev("unit_test", "premium-documents.test.ts / renderers.test.ts", "deterministic PDF/DOCX render")] },
  { id: "offer.negotiation", domain: "offer", operation: "negotiation", label: "Offer negotiation workflow", lifecycleStages: ["hiring"], autonomy: "prepare_draft", implementation: "MISSING", risk: risk("medium") },
  { id: "offer.right_to_work", domain: "offer", operation: "right_to_work", label: "Right-to-work / work-authorization verification", lifecycleStages: ["hiring", "compliance"], autonomy: "prepare_draft", implementation: "MISSING", risk: risk("high", { legalSensitivity: "high" }), countryRuleDependencies: [{ ruleFamily: "right_to_work", required: true }] },
  { id: "offer.signature_collection", domain: "offer", operation: "signature_collection", label: "Collect offer/pre-hire signatures", lifecycleStages: ["hiring"], autonomy: "execute_with_validation", implementation: "PARTIAL", risk: risk("high"), integrationDependencies: [{ system: "signature_provider", status: "blocked", notes: "Yousign external blocker P8.7.4" }] },
  { id: "offer.candidate_to_employee", domain: "offer", operation: "candidate_to_employee", label: "Convert candidate → employee (onboarding handoff)", lifecycleStages: ["hiring", "onboarding"], autonomy: "execute_with_validation", implementation: "PARTIAL", risk: risk("medium"), implementationReferences: [mod("src/lib/pierre/hr/workflows.ts"), mod("src/lib/pierre/v1/employees.ts")], evidence: [] },

  // ══ D. CONTRACTS & CONTRACTUAL CHANGES ═════════════════════════════════════
  { id: "contract.create", domain: "contract", operation: "create", label: "Create employment contract", lifecycleStages: ["contract"], autonomy: "prepare_draft", implementation: "VERIFIED_EXISTING", risk: risk("high", { legalSensitivity: "high", reversibility: "partially_reversible" }), implementationReferences: [mod("src/lib/pierre/v1/contracts.ts", "createContract"), mod("src/lib/pierre/v1/contract-state.ts")], evidence: [ev("integration_test", "runtime-core.itest.ts / hr-contracts.test.ts", "contract state machine + audit events")], countryRuleDependencies: [{ ruleFamily: "contract_types", required: true }] },
  { id: "contract.submit_review", domain: "contract", operation: "submit_review", label: "Submit contract for review", lifecycleStages: ["contract"], autonomy: "execute_autonomous", implementation: "VERIFIED_EXISTING", risk: risk("medium"), implementationReferences: [mod("src/lib/pierre/v1/contracts.ts")], evidence: [ev("state_machine", "contract-state.ts", "draft→under_review transition")] },
  { id: "contract.request_changes", domain: "contract", operation: "request_changes", label: "Request contract changes", lifecycleStages: ["contract"], autonomy: "execute_autonomous", implementation: "VERIFIED_EXISTING", risk: risk("low"), implementationReferences: [mod("src/lib/pierre/v1/contracts.ts")], evidence: [ev("state_machine", "contract-state.ts", "changes_requested transition")] },
  { id: "contract.approve", domain: "contract", operation: "approve", label: "Approve employment contract", lifecycleStages: ["contract"], autonomy: "execute_with_validation", implementation: "VERIFIED_EXISTING", risk: risk("high", { legalSensitivity: "high" }), approvals: [{ when: "always", approver: "hr_manager", reason: "contract approval is governed" }], implementationReferences: [mod("src/lib/pierre/v1/contracts.ts")], evidence: [ev("state_machine", "contract-state.ts", "approval transition + audit")] },
  { id: "contract.finalize", domain: "contract", operation: "finalize", label: "Finalize contract to final status", lifecycleStages: ["contract"], autonomy: "execute_with_validation", implementation: "VERIFIED_EXISTING", risk: risk("high", { reversibility: "irreversible" }), implementationReferences: [mod("src/lib/pierre/v1/contracts.ts")], evidence: [ev("integration_test", "hr-contracts.test.ts", "finalize requires hash/rendered artifact")] },
  { id: "contract.generate_artifacts", domain: "contract", operation: "generate_artifacts", label: "Generate contract PDF/DOCX", lifecycleStages: ["contract"], autonomy: "execute_autonomous", implementation: "VERIFIED_EXISTING", risk: risk("low"), implementationReferences: [mod("src/lib/pierre/v1/contracts.ts"), mod("src/lib/pierre/v1/renderers.ts")], evidence: [ev("unit_test", "renderers.test.ts", "deterministic content_hash")] },
  { id: "contract.readiness_check", domain: "contract", operation: "readiness_check", label: "Check contract readiness before action", lifecycleStages: ["contract"], autonomy: "execute_autonomous", implementation: "VERIFIED_EXISTING", risk: risk("low"), implementationReferences: [mod("src/lib/pierre/v1/contract-readiness.ts")], evidence: [ev("integration_test", "hr-contracts.test.ts", "readiness gating")] },
  { id: "contract.create_amendment", domain: "contract", operation: "create_amendment", label: "Create contract amendment (avenant)", lifecycleStages: ["contract", "mobility"], autonomy: "prepare_draft", implementation: "VERIFIED_EXISTING", risk: risk("high", { legalSensitivity: "high" }), implementationReferences: [mod("src/lib/pierre/v1/contracts.ts")], evidence: [ev("integration_test", "hr-contracts.test.ts", "amendment creation")] },
  { id: "contract.apply_amendment_effects", domain: "contract", operation: "apply_amendment_effects", label: "Apply amendment effects to employee record", lifecycleStages: ["contract"], autonomy: "execute_with_validation", implementation: "VERIFIED_EXISTING", risk: risk("high"), implementationReferences: [mod("src/lib/pierre/v1/signatures.ts")], evidence: [ev("state_machine", "signatures.ts", "amendment effect application worker")] },
  { id: "contract.schedule_amendment", domain: "contract", operation: "schedule_amendment", label: "Schedule future amendment activation", lifecycleStages: ["contract", "proactive"], autonomy: "execute_autonomous", implementation: "VERIFIED_EXISTING", risk: risk("medium"), implementationReferences: [mod("src/lib/pierre/v1/signatures.ts")], evidence: [ev("state_machine", "signatures.ts", "scheduled activation")] },
  { id: "contract.versioning", domain: "contract", operation: "versioning", label: "Contract versioning", lifecycleStages: ["contract", "archival"], autonomy: "execute_autonomous", implementation: "VERIFIED_EXISTING", risk: risk("low"), implementationReferences: [mod("src/lib/pierre/v1/documents.ts")], evidence: [ev("integration_test", "hr-contracts.test.ts", "version rows")] },
  { id: "contract.renewal", domain: "contract", operation: "renewal", label: "Contract renewal", lifecycleStages: ["contract", "proactive"], autonomy: "prepare_draft", implementation: "PARTIAL", risk: risk("high", { legalSensitivity: "high" }), countryRuleDependencies: [{ ruleFamily: "fixed_term_rules", required: true }] },
  { id: "contract.role_change", domain: "contract", operation: "role_change", label: "Role change (via amendment)", lifecycleStages: ["contract", "mobility"], autonomy: "prepare_draft", implementation: "PARTIAL", risk: risk("high", { legalSensitivity: "high" }) },
  { id: "contract.salary_change", domain: "contract", operation: "salary_change", label: "Salary change (via amendment)", lifecycleStages: ["contract", "compensation"], autonomy: "prepare_draft", implementation: "PARTIAL", risk: risk("high", { legalSensitivity: "high" }) },
  { id: "contract.hours_change", domain: "contract", operation: "hours_change", label: "Working-hours change (via amendment)", lifecycleStages: ["contract"], autonomy: "prepare_draft", implementation: "PARTIAL", risk: risk("high", { legalSensitivity: "high" }), countryRuleDependencies: [{ ruleFamily: "working_time", required: true }] },
  { id: "contract.suspension", domain: "contract", operation: "suspension", label: "Contract suspension", lifecycleStages: ["contract"], autonomy: "prepare_draft", implementation: "MISSING", risk: risk("high", { legalSensitivity: "high" }) },
  { id: "contract.end_probation", domain: "contract", operation: "end_probation", label: "End of probation decision", lifecycleStages: ["contract", "onboarding"], autonomy: "execute_with_validation", implementation: "PARTIAL", risk: risk("high", { legalSensitivity: "high" }), countryRuleDependencies: [{ ruleFamily: "probation_periods", required: true }] },
  { id: "contract.expiration", domain: "contract", operation: "expiration", label: "Contract expiration handling", lifecycleStages: ["contract", "proactive"], autonomy: "prepare_draft", implementation: "PARTIAL", risk: risk("high") },
  { id: "contract.archive", domain: "contract", operation: "archive", label: "Archive contract", lifecycleStages: ["archival"], autonomy: "execute_autonomous", implementation: "VERIFIED_EXISTING", risk: risk("low"), implementationReferences: [mod("src/lib/pierre/v1/documents.ts")], evidence: [ev("state_machine", "documents.ts", "status archived")] },
  { id: "contract.template_manage", domain: "contract", operation: "template_manage", label: "Manage contract templates & versions (governed, immutable published)", lifecycleStages: ["contract", "policy"], autonomy: "execute_with_validation", implementation: "VERIFIED_EXISTING", risk: risk("medium"), implementationReferences: [mod("src/lib/pierre/v1/templates.ts"), mod("src/lib/pierre/v1/contract-template-compiler.ts")], evidence: [ev("integration_test", "p83-template-security-corrections.test.ts", "template versioning + fingerprint drift + masking")] },

  // ── Signatures (part of contract lifecycle) ──
  { id: "contract.prepare_signature", domain: "contract", operation: "prepare_signature", label: "Prepare contract for signature (idempotent)", lifecycleStages: ["contract"], autonomy: "execute_with_validation", implementation: "VERIFIED_EXISTING", risk: risk("high"), implementationReferences: [mod("src/lib/pierre/v1/contracts.ts"), mod("src/lib/pierre/v1/signature-security.ts")], evidence: [ev("unit_test", "p87-signature-external-id.test.ts", "idempotent signature preparation")] },
  { id: "contract.submit_signature", domain: "contract", operation: "submit_signature", label: "Submit contract to e-signature provider", lifecycleStages: ["contract"], autonomy: "execute_with_validation", implementation: "EXTERNAL_DEPENDENCY", risk: risk("high", { legalSensitivity: "high" }), integrationDependencies: [{ system: "signature_provider", status: "blocked", notes: "Yousign sandbox org-membership blocker (P8.7.4) — live signature unblock NOT AUTHORIZED" }], implementationReferences: [mod("src/lib/pierre/v1/signatures.ts"), mod("src/lib/pierre/v1/signature-provider.ts")], evidence: [ev("unit_test", "p87-signature-external-id.test.ts", "submission plumbing verified; live provider blocked")] },
  { id: "contract.ingest_signature_webhook", domain: "contract", operation: "ingest_signature_webhook", label: "Ingest & reconcile signature webhook", lifecycleStages: ["contract"], autonomy: "execute_autonomous", implementation: "VERIFIED_EXISTING", risk: risk("high"), implementationReferences: [mod("src/lib/pierre/v1/signature-webhooks.ts"), mod("src/lib/pierre/v1/signature-events.ts")], evidence: [ev("state_machine", "signature-events.ts", "provider→canonical mapping + reconciliation")] },
  { id: "contract.finalize_signed", domain: "contract", operation: "finalize_signed", label: "Finalize signed contract with evidence", lifecycleStages: ["contract"], autonomy: "execute_autonomous", implementation: "VERIFIED_EXISTING", risk: risk("high", { reversibility: "irreversible" }), implementationReferences: [mod("src/lib/pierre/v1/signatures.ts")], evidence: [ev("integration_test", "signature evidence artifacts", "evidence recorded + integrity verify")] },
  { id: "contract.signature_security_tier", domain: "contract", operation: "signature_security_tier", label: "Enforce signature level (SES/AES/QES) security matrix", lifecycleStages: ["contract", "compliance"], autonomy: "execute_autonomous", implementation: "VERIFIED_EXISTING", risk: risk("high", { legalSensitivity: "high" }), implementationReferences: [mod("src/lib/pierre/v1/signature-security.ts")], evidence: [ev("integration_test", "signature-security tests", "SES/AES/QES matrix enforced")] },

  // ══ E. ONBOARDING ══════════════════════════════════════════════════════════
  { id: "onboarding.get_session", domain: "onboarding", operation: "get_session", label: "Get onboarding session state + steps", lifecycleStages: ["onboarding"], autonomy: "execute_autonomous", implementation: "VERIFIED_EXISTING", risk: risk("low"), implementationReferences: [mod("src/lib/pierre/v1/onboarding-service.ts")], evidence: [ev("integration_test", "onboarding tests", "server-authoritative session state")] },
  { id: "onboarding.complete_step", domain: "onboarding", operation: "complete_step", label: "Complete onboarding step (server-verified + evidence hash)", lifecycleStages: ["onboarding"], autonomy: "execute_with_validation", implementation: "VERIFIED_EXISTING", risk: risk("medium"), implementationReferences: [mod("src/lib/pierre/v1/onboarding-service.ts"), mod("src/lib/pierre/v1/onboarding-completion-rules.ts")], evidence: [ev("integration_test", "onboarding-completion-rules", "server-authoritative verification + evidence hash")] },
  { id: "onboarding.reopen_step", domain: "onboarding", operation: "reopen_step", label: "Reopen completed step (governed recovery)", lifecycleStages: ["onboarding"], autonomy: "execute_with_validation", implementation: "VERIFIED_EXISTING", risk: risk("medium"), implementationReferences: [mod("src/lib/pierre/v1/onboarding-service.ts")], evidence: [ev("state_machine", "onboarding-service.ts", "reopen transition")] },
  { id: "onboarding.complete_session", domain: "onboarding", operation: "complete_session", label: "Complete onboarding session (READY gate)", lifecycleStages: ["onboarding"], autonomy: "execute_with_validation", implementation: "VERIFIED_EXISTING", risk: risk("medium"), implementationReferences: [mod("src/lib/pierre/v1/onboarding-service.ts")], evidence: [ev("integration_test", "onboarding readiness gate", "blocker check before completion")] },
  { id: "onboarding.registry_steps", domain: "onboarding", operation: "registry_steps", label: "Canonical onboarding step registry", lifecycleStages: ["onboarding"], autonomy: "execute_autonomous", implementation: "VERIFIED_EXISTING", risk: risk("low"), implementationReferences: [mod("src/lib/pierre/v1/onboarding-registry.ts")], evidence: [ev("integration_test", "onboarding-registry", "10 canonical steps + dependencies")] },
  { id: "onboarding.employee_onboarding_plan", domain: "onboarding", operation: "employee_onboarding_plan", label: "Employee onboarding plan (preboarding, access, equipment, buddy, checkpoints)", lifecycleStages: ["onboarding"], autonomy: "prepare_draft", implementation: "PARTIAL", risk: risk("medium"), evidence: [] },
  { id: "onboarding.document_collection", domain: "onboarding", operation: "document_collection", label: "Onboarding document collection & chase", lifecycleStages: ["onboarding"], autonomy: "execute_with_validation", implementation: "PARTIAL", risk: risk("medium") },
  { id: "onboarding.access_provisioning", domain: "onboarding", operation: "access_provisioning", label: "Account/access provisioning", lifecycleStages: ["onboarding"], autonomy: "prepare_draft", implementation: "MISSING", risk: risk("medium"), integrationDependencies: [{ system: "identity_provider", status: "not_integrated" }] },
  { id: "onboarding.incomplete_handling", domain: "onboarding", operation: "incomplete_handling", label: "Detect & escalate incomplete onboarding", lifecycleStages: ["onboarding", "proactive"], autonomy: "execute_autonomous", implementation: "PARTIAL", risk: risk("low") },
  { id: "onboarding.probation_tracking", domain: "onboarding", operation: "probation_tracking", label: "Probation checkpoints & end-of-probation prompt", lifecycleStages: ["onboarding", "proactive"], autonomy: "execute_autonomous", implementation: "PARTIAL", risk: risk("medium"), countryRuleDependencies: [{ ruleFamily: "probation_periods", required: true }] },

  // ══ F. EMPLOYEE 360 & ADMINISTRATION ═══════════════════════════════════════
  { id: "employee360.create", domain: "employee360", operation: "create", label: "Create employee with identity", lifecycleStages: ["daily_admin", "hiring"], autonomy: "execute_with_validation", implementation: "VERIFIED_EXISTING", risk: risk("medium", { dataSensitivity: "sensitive" }), implementationReferences: [mod("src/lib/pierre/v1/employees.ts", "createEmployee")], evidence: [ev("integration_test", "hr-employee.test.ts / tenancy-rbac-employee360.itest.ts", "create + RBAC")] },
  { id: "employee360.list", domain: "employee360", operation: "list", label: "List employees (site-scoped, paginated)", lifecycleStages: ["daily_admin"], autonomy: "execute_autonomous", implementation: "VERIFIED_EXISTING", risk: risk("low"), implementationReferences: [mod("src/lib/pierre/v1/employees.ts")], evidence: [ev("integration_test", "tenancy-rbac-employee360.itest.ts", "site-scoped pagination")] },
  { id: "employee360.view_360", domain: "employee360", operation: "view_360", label: "Employee 360 view (events, documents, absences)", lifecycleStages: ["daily_admin"], autonomy: "execute_autonomous", implementation: "VERIFIED_EXISTING", risk: risk("medium", { dataSensitivity: "sensitive" }), implementationReferences: [mod("src/lib/pierre/v1/employees.ts")], evidence: [ev("integration_test", "hr-employee-file.test.ts", "aggregated 360 view")] },
  { id: "employee360.search", domain: "employee360", operation: "search", label: "Search employees (accent/typo tolerant)", lifecycleStages: ["daily_admin"], autonomy: "execute_autonomous", implementation: "VERIFIED_EXISTING", risk: risk("low"), implementationReferences: [mod("src/lib/pierre/v1/employee-search.ts")], evidence: [ev("integration_test", "employee-360-scale.bench.ts", "search at scale")] },
  { id: "employee360.update", domain: "employee360", operation: "update", label: "Update employee (identity, contact, role, dates)", lifecycleStages: ["daily_admin"], autonomy: "execute_with_validation", implementation: "VERIFIED_EXISTING", risk: risk("medium", { dataSensitivity: "sensitive" }), implementationReferences: [mod("src/lib/pierre/v1/employees.ts")], evidence: [ev("integration_test", "hr-employee.test.ts", "patch + field policies")] },
  { id: "employee360.archive", domain: "employee360", operation: "archive", label: "Archive employee (mark as left)", lifecycleStages: ["offboarding"], autonomy: "execute_with_validation", implementation: "VERIFIED_EXISTING", risk: risk("medium", { reversibility: "partially_reversible" }), implementationReferences: [mod("src/lib/pierre/v1/employees.ts")], evidence: [ev("state_machine", "employees.ts", "status left + archived_at")] },
  { id: "employee360.reactivate", domain: "employee360", operation: "reactivate", label: "Reactivate employee", lifecycleStages: ["daily_admin"], autonomy: "execute_with_validation", implementation: "VERIFIED_EXISTING", risk: risk("medium"), implementationReferences: [mod("src/lib/pierre/v1/employees.ts")], evidence: [ev("state_machine", "employees.ts", "left/suspended→active")] },
  { id: "employee360.timeline", domain: "employee360", operation: "timeline", label: "Employee timeline (events + status history)", lifecycleStages: ["daily_admin", "reporting"], autonomy: "execute_autonomous", implementation: "VERIFIED_EXISTING", risk: risk("low"), implementationReferences: [mod("src/lib/pierre/v1/employees.ts")], evidence: [ev("integration_test", "hr-employee-file.test.ts", "chronological timeline")] },
  { id: "employee360.completeness", domain: "employee360", operation: "completeness", label: "Employee completeness score + blocking items", lifecycleStages: ["daily_admin", "proactive"], autonomy: "execute_autonomous", implementation: "VERIFIED_EXISTING", risk: risk("low"), implementationReferences: [mod("src/lib/pierre/v1/completeness.ts")], evidence: [ev("integration_test", "completeness tests", "score + blockers")] },
  { id: "employee360.sensitive_data", domain: "employee360", operation: "sensitive_data", label: "Manage sensitive data (restricted access + audit)", lifecycleStages: ["daily_admin", "compliance"], autonomy: "execute_with_validation", implementation: "VERIFIED_EXISTING", risk: risk("high", { dataSensitivity: "restricted" }), implementationReferences: [mod("src/lib/pierre/v1/employee-sensitive.ts")], evidence: [ev("integration_test", "gdpr / sensitive access log", "restricted access + audit trail")] },
  { id: "employee360.documents_list", domain: "employee360", operation: "documents_list", label: "List employee documents (metadata only)", lifecycleStages: ["daily_admin"], autonomy: "execute_autonomous", implementation: "VERIFIED_EXISTING", risk: risk("low"), implementationReferences: [mod("src/lib/pierre/v1/employees.ts")], evidence: [ev("integration_test", "hr-employee-file.test.ts", "metadata-only listing")] },
  { id: "employee360.import", domain: "employee360", operation: "import", label: "Bulk employee import (validated batches)", lifecycleStages: ["daily_admin"], autonomy: "execute_with_validation", implementation: "VERIFIED_EXISTING", risk: risk("medium", { dataSensitivity: "sensitive" }), implementationReferences: [mod("src/lib/pierre/v1/employee-import.ts")], evidence: [ev("integration_test", "employee-import-scale.bench.ts", "batch import at scale")] },
  { id: "employee360.custom_fields", domain: "employee360", operation: "custom_fields", label: "Custom field definitions & values", lifecycleStages: ["daily_admin"], autonomy: "execute_with_validation", implementation: "VERIFIED_EXISTING", risk: risk("low"), implementationReferences: [mod("src/lib/pierre/v1/custom-fields.ts")], evidence: [ev("migration_table", "pierre_rt_custom_field_definitions", "custom fields schema")] },
  { id: "employee360.rectify", domain: "employee360", operation: "rectify", label: "Rectify employee data (GDPR correction)", lifecycleStages: ["daily_admin", "compliance"], autonomy: "execute_with_validation", implementation: "VERIFIED_EXISTING", risk: risk("medium", { dataSensitivity: "sensitive" }), implementationReferences: [mod("src/lib/pierre/v1/employees.ts")], evidence: [ev("integration_test", "gdpr rectification", "correction + audit")] },

  // ══ G. ABSENCES, LEAVE & TIME ══════════════════════════════════════════════
  { id: "absence.create_request", domain: "absence", operation: "create_request", label: "Create absence request", lifecycleStages: ["absence_time"], autonomy: "execute_with_validation", implementation: "VERIFIED_EXISTING", risk: risk("low"), implementationReferences: [mod("src/lib/pierre/v1/employees.ts"), route("src/app/api/pierre/v1/employees")], evidence: [ev("migration_table", "pierre_rt_employee_absences", "absence rows + create path")] },
  { id: "absence.list", domain: "absence", operation: "list", label: "List employee absences", lifecycleStages: ["absence_time"], autonomy: "execute_autonomous", implementation: "VERIFIED_EXISTING", risk: risk("low"), implementationReferences: [mod("src/lib/pierre/v1/employees.ts")], evidence: [ev("integration_test", "hr-employee-file.test.ts", "absence listing")] },
  { id: "absence.approval_workflow", domain: "absence", operation: "approval_workflow", label: "Absence approval workflow (manager/HR)", lifecycleStages: ["absence_time"], autonomy: "execute_with_validation", implementation: "MISSING", risk: risk("medium") },
  { id: "absence.balance_calculation", domain: "absence", operation: "balance_calculation", label: "Leave balance calculation & accrual", lifecycleStages: ["absence_time"], autonomy: "execute_autonomous", implementation: "MISSING", risk: risk("medium"), countryRuleDependencies: [{ ruleFamily: "paid_leave", required: true }] },
  { id: "absence.conflict_detection", domain: "absence", operation: "conflict_detection", label: "Absence conflict/overlap detection & planning", lifecycleStages: ["absence_time"], autonomy: "execute_autonomous", implementation: "MISSING", risk: risk("low") },
  { id: "absence.sick_leave", domain: "absence", operation: "sick_leave", label: "Sick leave & medical certificate handling", lifecycleStages: ["absence_time"], autonomy: "prepare_draft", implementation: "PARTIAL", risk: risk("medium", { dataSensitivity: "sensitive" }), countryRuleDependencies: [{ ruleFamily: "sick_leave", required: true }] },
  { id: "absence.parental_leave", domain: "absence", operation: "parental_leave", label: "Maternity/paternity/parental leave", lifecycleStages: ["absence_time"], autonomy: "prepare_draft", implementation: "MISSING", risk: risk("high", { legalSensitivity: "high" }), countryRuleDependencies: [{ ruleFamily: "parental_leave", required: true }] },
  { id: "absence.return_to_work", domain: "absence", operation: "return_to_work", label: "Return-to-work & accommodation", lifecycleStages: ["absence_time", "health_safety"], autonomy: "prepare_draft", implementation: "MISSING", risk: risk("high", { dataSensitivity: "sensitive", legalSensitivity: "high" }), countryRuleDependencies: [{ ruleFamily: "occupational_health", required: true }] },
  { id: "absence.time_tracking", domain: "absence", operation: "time_tracking", label: "Working time / hours / schedules / on-call", lifecycleStages: ["absence_time"], autonomy: "prepare_draft", implementation: "PARTIAL", risk: risk("medium"), countryRuleDependencies: [{ ruleFamily: "working_time", required: true }] },
  { id: "absence.timeclock_integration", domain: "absence", operation: "timeclock_integration", label: "Time-clock integration", lifecycleStages: ["absence_time"], autonomy: "prepare_draft", implementation: "MISSING", risk: risk("low"), integrationDependencies: [{ system: "none", status: "not_integrated", notes: "time & attendance system" }] },
  { id: "absence.payroll_transmission", domain: "absence", operation: "payroll_transmission", label: "Transmit absences to payroll", lifecycleStages: ["absence_time", "payroll"], autonomy: "execute_with_validation", implementation: "MISSING", risk: risk("medium") },

  // ══ H. PAYROLL OPERATIONAL ═════════════════════════════════════════════════
  { id: "payroll.collect_variables", domain: "payroll", operation: "collect_variables", label: "Collect payroll variables (hours, premiums, bonuses)", lifecycleStages: ["payroll"], autonomy: "prepare_draft", implementation: "IMPLEMENTED_UNVERIFIED", risk: risk("high"), evidence: [] },
  { id: "payroll.absence_recap", domain: "payroll", operation: "absence_recap", label: "Absence recap for a payroll period", lifecycleStages: ["payroll"], autonomy: "prepare_draft", implementation: "IMPLEMENTED_UNVERIFIED", risk: risk("medium") },
  { id: "payroll.anomaly_detection", domain: "payroll", operation: "anomaly_detection", label: "Payroll data anomaly detection", lifecycleStages: ["payroll", "proactive"], autonomy: "execute_autonomous", implementation: "CONTRACT_ONLY", risk: risk("high") },
  { id: "payroll.validation", domain: "payroll", operation: "validation", label: "Payroll variables validation before transmission", lifecycleStages: ["payroll"], autonomy: "execute_with_validation", implementation: "MISSING", risk: risk("high"), approvals: [{ when: "always", approver: "payroll_operator", reason: "payroll validation must be human-confirmed" }] },
  { id: "payroll.export_transmission", domain: "payroll", operation: "export_transmission", label: "Export & transmit to payroll provider", lifecycleStages: ["payroll"], autonomy: "execute_with_validation", implementation: "EXTERNAL_DEPENDENCY", risk: risk("high", { legalSensitivity: "high" }), integrationDependencies: [{ system: "payroll_provider", status: "not_integrated" }], countryRuleDependencies: [{ ruleFamily: "payroll_contributions", required: true }] },
  { id: "payroll.official_calculation", domain: "payroll", operation: "official_calculation", label: "Official payroll calculation (certified engine)", lifecycleStages: ["payroll"], autonomy: "observe_only", implementation: "EXTERNAL_DEPENDENCY", risk: risk("critical", { legalSensitivity: "high", reasons: ["certified computation not Pierre's role"] }), integrationDependencies: [{ system: "payroll_provider", status: "not_integrated" }], countryRuleDependencies: [{ ruleFamily: "payroll_contributions", required: true }] },
  { id: "payroll.dsn_declaration", domain: "payroll", operation: "dsn_declaration", label: "Social declaration submission (e.g. DSN/ONSS/CCSS)", lifecycleStages: ["payroll", "compliance"], autonomy: "observe_only", implementation: "EXTERNAL_DEPENDENCY", risk: risk("critical", { legalSensitivity: "high" }), integrationDependencies: [{ system: "payroll_provider", status: "not_integrated" }], countryRuleDependencies: [{ ruleFamily: "payroll_contributions", required: true }] },
  { id: "payroll.payslip_generation", domain: "payroll", operation: "payslip_generation", label: "Payslip generation", lifecycleStages: ["payroll"], autonomy: "observe_only", implementation: "EXTERNAL_DEPENDENCY", risk: risk("high", { legalSensitivity: "high" }), integrationDependencies: [{ system: "payroll_provider", status: "not_integrated" }], countryRuleDependencies: [{ ruleFamily: "payslip_requirements", required: true }] },
  { id: "payroll.payslip_distribution", domain: "payroll", operation: "payslip_distribution", label: "Secure payslip distribution", lifecycleStages: ["payroll"], autonomy: "execute_with_validation", implementation: "PARTIAL", risk: risk("high", { dataSensitivity: "restricted" }), implementationReferences: [mod("src/lib/pierre/v1/communication-secure-links.ts")] },
  { id: "payroll.provider_reconciliation", domain: "payroll", operation: "provider_reconciliation", label: "Reconcile provider return", lifecycleStages: ["payroll"], autonomy: "execute_with_validation", implementation: "MISSING", risk: risk("high"), integrationDependencies: [{ system: "payroll_provider", status: "not_integrated" }] },
  { id: "payroll.calendar", domain: "payroll", operation: "calendar", label: "Payroll calendar & cutoffs", lifecycleStages: ["payroll", "proactive"], autonomy: "execute_autonomous", implementation: "MISSING", risk: risk("medium") },
  { id: "payroll.correction", domain: "payroll", operation: "correction", label: "Payroll correction / rappel", lifecycleStages: ["payroll"], autonomy: "execute_with_validation", implementation: "MISSING", risk: risk("high") },

  // ══ I. COMPENSATION & BENEFITS ═════════════════════════════════════════════
  { id: "compensation.salary_grid", domain: "compensation", operation: "salary_grid", label: "Salary grid maintenance", lifecycleStages: ["compensation"], autonomy: "prepare_draft", implementation: "MISSING", risk: risk("medium") },
  { id: "compensation.salary_change_prepare", domain: "compensation", operation: "salary_change_prepare", label: "Prepare salary change (feeds contract amendment)", lifecycleStages: ["compensation", "contract"], autonomy: "prepare_draft", implementation: "PARTIAL", risk: risk("high", { legalSensitivity: "high" }) },
  { id: "compensation.raise_promotion", domain: "compensation", operation: "raise_promotion", label: "Raise / promotion compensation", lifecycleStages: ["compensation", "career"], autonomy: "prepare_draft", implementation: "MISSING", risk: risk("high") },
  { id: "compensation.variable_pay", domain: "compensation", operation: "variable_pay", label: "Variable pay (bonus, commission, incentive)", lifecycleStages: ["compensation"], autonomy: "prepare_draft", implementation: "MISSING", risk: risk("high") },
  { id: "compensation.equity", domain: "compensation", operation: "equity", label: "Equity (options/RSUs) administration", lifecycleStages: ["compensation"], autonomy: "prepare_draft", implementation: "MISSING", risk: risk("high", { legalSensitivity: "high" }) },
  { id: "compensation.benefits", domain: "compensation", operation: "benefits", label: "Benefits administration (mutuelle, prévoyance)", lifecycleStages: ["compensation"], autonomy: "prepare_draft", implementation: "MISSING", risk: risk("medium"), integrationDependencies: [{ system: "benefits_provider", status: "not_integrated" }] },
  { id: "compensation.vouchers", domain: "compensation", operation: "vouchers", label: "Meal vouchers / titres", lifecycleStages: ["compensation"], autonomy: "prepare_draft", implementation: "MISSING", risk: risk("low") },
  { id: "compensation.expenses", domain: "compensation", operation: "expenses", label: "Expense reimbursement", lifecycleStages: ["compensation"], autonomy: "execute_with_validation", implementation: "MISSING", risk: risk("medium") },
  { id: "compensation.salary_review", domain: "compensation", operation: "salary_review", label: "Salary review campaign", lifecycleStages: ["compensation"], autonomy: "prepare_draft", implementation: "MISSING", risk: risk("high") },
  { id: "compensation.pay_equity", domain: "compensation", operation: "pay_equity", label: "Pay-equity analysis & reporting", lifecycleStages: ["compensation", "reporting", "compliance"], autonomy: "observe_only", implementation: "MISSING", risk: risk("high", { legalSensitivity: "high" }), countryRuleDependencies: [{ ruleFamily: "collective_agreements", required: false }] },

  // ══ J. PERFORMANCE ═════════════════════════════════════════════════════════
  { id: "performance.objectives", domain: "performance", operation: "objectives", label: "Create & track objectives (OKRs/goals)", lifecycleStages: ["performance"], autonomy: "prepare_draft", implementation: "MISSING", risk: risk("low") },
  { id: "performance.annual_review", domain: "performance", operation: "annual_review", label: "Annual/professional interview workflow", lifecycleStages: ["performance"], autonomy: "prepare_draft", implementation: "MISSING", risk: risk("medium"), countryRuleDependencies: [{ ruleFamily: "mandatory_trainings", required: false }] },
  { id: "performance.feedback_360", domain: "performance", operation: "feedback_360", label: "360 feedback & peer review", lifecycleStages: ["performance"], autonomy: "prepare_draft", implementation: "MISSING", risk: risk("medium", { dataSensitivity: "sensitive" }) },
  { id: "performance.one_to_one", domain: "performance", operation: "one_to_one", label: "One-to-ones & performance notes", lifecycleStages: ["performance"], autonomy: "prepare_draft", implementation: "MISSING", risk: risk("low") },
  { id: "performance.calibration", domain: "performance", operation: "calibration", label: "Calibration & promotion committee support", lifecycleStages: ["performance", "career"], autonomy: "suggest", implementation: "MISSING", risk: risk("high", { dataSensitivity: "sensitive" }) },
  { id: "performance.pip", domain: "performance", operation: "pip", label: "Performance improvement plan (PIP)", lifecycleStages: ["performance", "disciplinary"], autonomy: "prepare_draft", implementation: "MISSING", risk: risk("high", { legalSensitivity: "high" }) },
  { id: "performance.recognition", domain: "performance", operation: "recognition", label: "Recognition & documentation", lifecycleStages: ["performance"], autonomy: "prepare_draft", implementation: "MISSING", risk: risk("low") },

  // ══ K. TRAINING & SKILLS ═══════════════════════════════════════════════════
  { id: "training.skills_mapping", domain: "training", operation: "skills_mapping", label: "Map required vs held skills / gap", lifecycleStages: ["training", "career"], autonomy: "prepare_draft", implementation: "MISSING", risk: risk("low") },
  { id: "training.plan", domain: "training", operation: "plan", label: "Create & track training plans", lifecycleStages: ["training"], autonomy: "prepare_draft", implementation: "IMPLEMENTED_UNVERIFIED", risk: risk("low"), implementationReferences: [route("src/app/api/pierre/use/workflows/rh")], evidence: [] },
  { id: "training.enrollment", domain: "training", operation: "enrollment", label: "Enroll employees & manage convocations", lifecycleStages: ["training"], autonomy: "execute_with_validation", implementation: "MISSING", risk: risk("low") },
  { id: "training.certification_tracking", domain: "training", operation: "certification_tracking", label: "Track certification validity & expiry", lifecycleStages: ["training", "proactive"], autonomy: "execute_autonomous", implementation: "MISSING", risk: risk("medium") },
  { id: "training.mandatory_compliance", domain: "training", operation: "mandatory_compliance", label: "Enforce mandatory training compliance & proof", lifecycleStages: ["training", "compliance", "health_safety"], autonomy: "execute_autonomous", implementation: "MISSING", risk: risk("high", { legalSensitivity: "high" }), countryRuleDependencies: [{ ruleFamily: "mandatory_trainings", required: true }] },
  { id: "training.evaluation", domain: "training", operation: "evaluation", label: "Post-training evaluation", lifecycleStages: ["training"], autonomy: "prepare_draft", implementation: "MISSING", risk: risk("low") },

  // ══ L. CAREER & MOBILITY ═══════════════════════════════════════════════════
  { id: "career.wishes", domain: "career", operation: "wishes", label: "Track career wishes & evolution paths", lifecycleStages: ["career"], autonomy: "prepare_draft", implementation: "MISSING", risk: risk("low", { dataSensitivity: "sensitive" }) },
  { id: "career.internal_mobility", domain: "career", operation: "internal_mobility", label: "Internal mobility requests & approval", lifecycleStages: ["career", "mobility"], autonomy: "prepare_draft", implementation: "MISSING", risk: risk("medium") },
  { id: "career.geographic_mobility", domain: "career", operation: "geographic_mobility", label: "Geographic mobility (site change)", lifecycleStages: ["mobility", "contract"], autonomy: "prepare_draft", implementation: "MISSING", risk: risk("high", { legalSensitivity: "high" }) },
  { id: "career.succession_transition", domain: "career", operation: "succession_transition", label: "Role transition & succession execution", lifecycleStages: ["career"], autonomy: "prepare_draft", implementation: "MISSING", risk: risk("medium", { dataSensitivity: "sensitive" }) },
  { id: "career.mentoring", domain: "career", operation: "mentoring", label: "Mentoring relationships & retention monitoring", lifecycleStages: ["career"], autonomy: "suggest", implementation: "MISSING", risk: risk("low") },

  // ══ M. EMPLOYEE RELATIONS ══════════════════════════════════════════════════
  { id: "relations.hr_requests", domain: "relations", operation: "hr_requests", label: "HR questions/requests ticketing", lifecycleStages: ["relations"], autonomy: "execute_with_validation", implementation: "MISSING", risk: risk("medium", { dataSensitivity: "sensitive" }) },
  { id: "relations.complaints", domain: "relations", operation: "complaints", label: "Log & resolve complaints/conflicts", lifecycleStages: ["relations"], autonomy: "prepare_draft", implementation: "MISSING", risk: risk("high", { dataSensitivity: "sensitive", legalSensitivity: "high" }) },
  { id: "relations.mediation", domain: "relations", operation: "mediation", label: "Mediation & escalation tracking", lifecycleStages: ["relations"], autonomy: "observe_only", implementation: "MISSING", risk: risk("high", { dataSensitivity: "sensitive" }) },
  { id: "relations.harassment_alert", domain: "relations", operation: "harassment_alert", label: "Harassment/discrimination alert intake (governed, confidential)", lifecycleStages: ["relations", "compliance"], autonomy: "observe_only", implementation: "MISSING", risk: risk("critical", { dataSensitivity: "restricted", legalSensitivity: "high", reasons: ["legally protected, human handling required"] }) },
  { id: "relations.whistleblower", domain: "relations", operation: "whistleblower", label: "Whistleblower protection & confidentiality", lifecycleStages: ["relations", "compliance"], autonomy: "human_only", implementation: "HUMAN_ONLY", risk: risk("critical", { dataSensitivity: "restricted", legalSensitivity: "high", reversibility: "irreversible" }), countryRuleDependencies: [{ ruleFamily: "data_protection", required: true }] },

  // ══ N. DISCIPLINARY ════════════════════════════════════════════════════════
  { id: "disciplinary.file_report", domain: "disciplinary", operation: "file_report", label: "File disciplinary report & collect facts/evidence", lifecycleStages: ["disciplinary"], autonomy: "prepare_draft", implementation: "PARTIAL", risk: risk("high", { dataSensitivity: "restricted", legalSensitivity: "high" }) },
  { id: "disciplinary.chain_of_custody", domain: "disciplinary", operation: "chain_of_custody", label: "Document chronology & evidence chain of custody", lifecycleStages: ["disciplinary", "compliance"], autonomy: "prepare_draft", implementation: "PARTIAL", risk: risk("high", { dataSensitivity: "restricted", reversibility: "irreversible" }) },
  { id: "disciplinary.qualify", domain: "disciplinary", operation: "qualify", label: "Analyze facts & qualify violation", lifecycleStages: ["disciplinary"], autonomy: "human_only", implementation: "HUMAN_ONLY", risk: risk("critical", { legalSensitivity: "high" }), countryRuleDependencies: [{ ruleFamily: "disciplinary_procedure", required: true }] },
  { id: "disciplinary.summons", domain: "disciplinary", operation: "summons", label: "Summon employee for disciplinary interview", lifecycleStages: ["disciplinary"], autonomy: "prepare_draft", implementation: "MISSING", risk: risk("high", { legalSensitivity: "high" }), countryRuleDependencies: [{ ruleFamily: "disciplinary_procedure", required: true }] },
  { id: "disciplinary.decision", domain: "disciplinary", operation: "decision", label: "Issue disciplinary decision/warning/sanction", lifecycleStages: ["disciplinary"], autonomy: "human_only", implementation: "HUMAN_ONLY", risk: risk("critical", { legalSensitivity: "high", reversibility: "irreversible" }), countryRuleDependencies: [{ ruleFamily: "disciplinary_procedure", required: true }] },
  { id: "disciplinary.appeal", domain: "disciplinary", operation: "appeal", label: "Manage disciplinary appeals", lifecycleStages: ["disciplinary"], autonomy: "prepare_draft", implementation: "MISSING", risk: risk("high", { legalSensitivity: "high" }) },
  { id: "disciplinary.deadlines", domain: "disciplinary", operation: "deadlines", label: "Enforce statutory disciplinary deadlines", lifecycleStages: ["disciplinary", "proactive"], autonomy: "execute_autonomous", implementation: "MISSING", risk: risk("high", { legalSensitivity: "high" }), countryRuleDependencies: [{ ruleFamily: "disciplinary_procedure", required: true }] },
  { id: "disciplinary.closure", domain: "disciplinary", operation: "closure", label: "Track case closure & archive", lifecycleStages: ["disciplinary", "archival"], autonomy: "execute_with_validation", implementation: "MISSING", risk: risk("high", { dataSensitivity: "restricted" }) },

  // ══ O. HEALTH, SAFETY & WELLBEING ══════════════════════════════════════════
  { id: "health.medical_visits", domain: "health", operation: "medical_visits", label: "Manage mandatory occupational-health visits", lifecycleStages: ["health_safety", "proactive"], autonomy: "prepare_draft", implementation: "MISSING", risk: risk("high", { dataSensitivity: "restricted", legalSensitivity: "high" }), countryRuleDependencies: [{ ruleFamily: "occupational_health", required: true }] },
  { id: "health.incident_reporting", domain: "health", operation: "incident_reporting", label: "Report & track workplace incidents/accidents", lifecycleStages: ["health_safety", "compliance"], autonomy: "prepare_draft", implementation: "MISSING", risk: risk("high", { legalSensitivity: "high" }) },
  { id: "health.risk_assessment", domain: "health", operation: "risk_assessment", label: "Risk assessment & prevention planning", lifecycleStages: ["health_safety"], autonomy: "prepare_draft", implementation: "MISSING", risk: risk("high", { legalSensitivity: "high" }) },
  { id: "health.accommodations", domain: "health", operation: "accommodations", label: "Manage medical accommodations", lifecycleStages: ["health_safety"], autonomy: "prepare_draft", implementation: "MISSING", risk: risk("high", { dataSensitivity: "restricted", legalSensitivity: "high" }) },
  { id: "health.mental_health", domain: "health", operation: "mental_health", label: "Wellbeing / workload signals (never diagnostic)", lifecycleStages: ["health_safety"], autonomy: "observe_only", implementation: "MISSING", risk: risk("high", { dataSensitivity: "restricted", reasons: ["Pierre never acts as a physician"] }) },
  { id: "health.safety_clearances", domain: "health", operation: "safety_clearances", label: "Manage safety clearances & access restrictions", lifecycleStages: ["health_safety", "compliance"], autonomy: "prepare_draft", implementation: "MISSING", risk: risk("high") },
  { id: "health.mandatory_safety_training", domain: "health", operation: "mandatory_safety_training", label: "Track mandatory H&S training completion", lifecycleStages: ["health_safety", "training", "proactive"], autonomy: "execute_autonomous", implementation: "MISSING", risk: risk("high", { legalSensitivity: "high" }), countryRuleDependencies: [{ ruleFamily: "mandatory_trainings", required: true }] },

  // ══ P. HR COMMUNICATIONS ═══════════════════════════════════════════════════
  { id: "communications.send_in_app", domain: "communications", operation: "send_in_app", label: "Send in-app communication (governed)", lifecycleStages: ["communications"], autonomy: "execute_autonomous", implementation: "VERIFIED_EXISTING", risk: risk("low"), implementationReferences: [mod("src/lib/pierre/v1/communications.ts")], evidence: [ev("p8_proof", ".p89-proofs/p89-final-2fa5898d89", "40k deliveries governed, overlap=0")] },
  { id: "communications.send_email", domain: "communications", operation: "send_email", label: "Send email communication (governed, proof-of-send)", lifecycleStages: ["communications"], autonomy: "execute_autonomous", implementation: "VERIFIED_EXISTING", risk: risk("medium"), implementationReferences: [mod("src/lib/pierre/v1/communications.ts"), mod("src/lib/pierre/v1/communication-provider.ts")], evidence: [ev("p8_proof", ".p89-proofs/p89-final-2fa5898d89/communications.json", "governed claim/submit, dead-letter, provider events")] },
  { id: "communications.create_intent", domain: "communications", operation: "create_intent", label: "Create communication intent from outbox event", lifecycleStages: ["communications"], autonomy: "execute_autonomous", implementation: "VERIFIED_EXISTING", risk: risk("low"), implementationReferences: [mod("src/lib/pierre/v1/communications.ts")], evidence: [ev("state_machine", "communications.ts", "intent creation")] },
  { id: "communications.resolve_recipient", domain: "communications", operation: "resolve_recipient", label: "Resolve recipient (strategy-based)", lifecycleStages: ["communications"], autonomy: "execute_autonomous", implementation: "VERIFIED_EXISTING", risk: risk("low"), implementationReferences: [mod("src/lib/pierre/v1/communication-recipient-resolver.ts")], evidence: [ev("integration_test", "pierre-channels-b33.test.ts", "recipient resolution")] },
  { id: "communications.preferences", domain: "communications", operation: "preferences", label: "Communication preferences per user/category/channel", lifecycleStages: ["communications"], autonomy: "execute_with_validation", implementation: "VERIFIED_EXISTING", risk: risk("low"), implementationReferences: [mod("src/lib/pierre/v1/communications.ts")], evidence: [ev("migration_table", "pierre_rt_communication_preferences", "prefs schema")] },
  { id: "communications.suppression", domain: "communications", operation: "suppression", label: "Suppress address (bounce/complaint)", lifecycleStages: ["communications"], autonomy: "execute_autonomous", implementation: "VERIFIED_EXISTING", risk: risk("medium"), implementationReferences: [mod("src/lib/pierre/v1/communications.ts")], evidence: [ev("migration_table", "pierre_rt_communication_suppressions", "suppression + governed insert")] },
  { id: "communications.provider_webhook", domain: "communications", operation: "provider_webhook", label: "Ingest & apply provider webhook (idempotent, monotonic)", lifecycleStages: ["communications"], autonomy: "execute_autonomous", implementation: "VERIFIED_EXISTING", risk: risk("medium"), implementationReferences: [mod("src/lib/pierre/v1/communication-webhook-db.ts")], evidence: [ev("p8_proof", ".p89-proofs/p89-final-2fa5898d89", "provider events 25/25 duplicate+monotonic")] },
  { id: "communications.dead_letter", domain: "communications", operation: "dead_letter", label: "Dead-letter failed communications", lifecycleStages: ["communications"], autonomy: "execute_autonomous", implementation: "VERIFIED_EXISTING", risk: risk("medium"), implementationReferences: [mod("src/lib/pierre/v1/communications.ts")], evidence: [ev("p8_proof", ".p89-proofs/p89-final-2fa5898d89", "dead-letter under concurrency=1000")] },
  { id: "communications.retry_cancel", domain: "communications", operation: "retry_cancel", label: "Retry / cancel a delivery (governed)", lifecycleStages: ["communications"], autonomy: "execute_with_validation", implementation: "VERIFIED_EXISTING", risk: risk("low"), implementationReferences: [mod("src/lib/pierre/v1/communications.ts")], evidence: [ev("state_machine", "communications.ts", "retry/cancel functions")] },
  { id: "communications.secure_link", domain: "communications", operation: "secure_link", label: "Secure, time-limited, revocable document link", lifecycleStages: ["communications", "compliance"], autonomy: "execute_autonomous", implementation: "VERIFIED_EXISTING", risk: risk("medium", { dataSensitivity: "sensitive" }), implementationReferences: [mod("src/lib/pierre/v1/communication-secure-links.ts")], evidence: [ev("integration_test", "communication-secure-links", "time-limited revocable access")] },
  { id: "communications.templates", domain: "communications", operation: "templates", label: "Manage communication templates (multilingual, versioned)", lifecycleStages: ["communications", "policy"], autonomy: "execute_with_validation", implementation: "PARTIAL", risk: risk("low"), implementationReferences: [mod("src/lib/pierre/v1/communication-template-registry.ts")] },
  { id: "communications.scheduling", domain: "communications", operation: "scheduling", label: "Schedule comms (quiet hours, batch, delay)", lifecycleStages: ["communications", "proactive"], autonomy: "execute_autonomous", implementation: "PARTIAL", risk: risk("low") },
  { id: "communications.read_receipt", domain: "communications", operation: "read_receipt", label: "Track read receipt / engagement", lifecycleStages: ["communications"], autonomy: "execute_autonomous", implementation: "PARTIAL", risk: risk("low") },
  { id: "communications.legal_review", domain: "communications", operation: "legal_review", label: "Validate communication content for legal/compliance", lifecycleStages: ["communications", "compliance"], autonomy: "prepare_draft", implementation: "MISSING", risk: risk("high", { legalSensitivity: "high" }) },
  { id: "communications.audit_lifecycle", domain: "communications", operation: "audit_lifecycle", label: "Audit delivery lifecycle (PII-free)", lifecycleStages: ["communications", "compliance"], autonomy: "execute_autonomous", implementation: "VERIFIED_EXISTING", risk: risk("low"), implementationReferences: [mod("src/lib/pierre/v1/communications.ts")], evidence: [ev("integration_test", "communications audit", "PII-free CloneTrace")] },

  // ══ Q. POLICIES & INTERNAL COMPLIANCE ══════════════════════════════════════
  { id: "policy.define", domain: "policy", operation: "define", label: "Define an internal HR policy", lifecycleStages: ["policy"], autonomy: "prepare_draft", implementation: "CONTRACT_ONLY", risk: risk("medium") },
  { id: "policy.version_publish", domain: "policy", operation: "version_publish", label: "Version & publish policy updates", lifecycleStages: ["policy"], autonomy: "execute_with_validation", implementation: "MISSING", risk: risk("medium") },
  { id: "policy.acceptance", domain: "policy", operation: "acceptance", label: "Require & record policy acceptance (NDA, code of conduct)", lifecycleStages: ["policy", "compliance"], autonomy: "execute_with_validation", implementation: "MISSING", risk: risk("medium") },
  { id: "policy.impact_diffusion", domain: "policy", operation: "impact_diffusion", label: "Policy impact analysis & diffusion + proof", lifecycleStages: ["policy", "communications"], autonomy: "prepare_draft", implementation: "MISSING", risk: risk("low") },
  { id: "policy.enforcement_audit", domain: "policy", operation: "enforcement_audit", label: "Audit policy application & exceptions", lifecycleStages: ["policy", "compliance"], autonomy: "execute_autonomous", implementation: "MISSING", risk: risk("medium") },

  // ══ R. OFFBOARDING ═════════════════════════════════════════════════════════
  { id: "offboarding.resignation", domain: "offboarding", operation: "resignation", label: "Process resignation", lifecycleStages: ["offboarding"], autonomy: "prepare_draft", implementation: "MISSING", risk: risk("high", { legalSensitivity: "high" }), countryRuleDependencies: [{ ruleFamily: "notice_periods", required: true }] },
  { id: "offboarding.dismissal", domain: "offboarding", operation: "dismissal", label: "Dismissal procedure (governed, human+legal)", lifecycleStages: ["offboarding"], autonomy: "human_only", implementation: "HUMAN_ONLY", risk: risk("critical", { legalSensitivity: "high", reversibility: "irreversible" }), countryRuleDependencies: [{ ruleFamily: "dismissal_procedure", required: true }, { ruleFamily: "notice_periods", required: true }, { ruleFamily: "severance", required: true }] },
  { id: "offboarding.mutual_termination", domain: "offboarding", operation: "mutual_termination", label: "Mutual termination (or local equivalent)", lifecycleStages: ["offboarding"], autonomy: "prepare_draft", implementation: "MISSING", risk: risk("high", { legalSensitivity: "high" }), countryRuleDependencies: [{ ruleFamily: "severance", required: true }] },
  { id: "offboarding.end_of_contract", domain: "offboarding", operation: "end_of_contract", label: "End of fixed-term contract", lifecycleStages: ["offboarding"], autonomy: "prepare_draft", implementation: "PARTIAL", risk: risk("high"), countryRuleDependencies: [{ ruleFamily: "fixed_term_rules", required: true }] },
  { id: "offboarding.orchestrate", domain: "offboarding", operation: "orchestrate", label: "Orchestrate offboarding (access, handover, equipment, docs)", lifecycleStages: ["offboarding"], autonomy: "execute_with_validation", implementation: "MISSING", risk: risk("high") },
  { id: "offboarding.final_pay", domain: "offboarding", operation: "final_pay", label: "Prepare final pay & documents (STC)", lifecycleStages: ["offboarding", "payroll"], autonomy: "prepare_draft", implementation: "MISSING", risk: risk("high", { legalSensitivity: "high" }), countryRuleDependencies: [{ ruleFamily: "payroll_contributions", required: true }] },
  { id: "offboarding.exit_interview", domain: "offboarding", operation: "exit_interview", label: "Exit interview", lifecycleStages: ["offboarding"], autonomy: "prepare_draft", implementation: "MISSING", risk: risk("low") },
  { id: "offboarding.file_closure_archival", domain: "offboarding", operation: "file_closure_archival", label: "Close & archive employee file (retention)", lifecycleStages: ["offboarding", "archival"], autonomy: "execute_with_validation", implementation: "PARTIAL", risk: risk("medium"), countryRuleDependencies: [{ ruleFamily: "document_retention", required: true }] },

  // ══ S. DATA, PRIVACY & GDPR ════════════════════════════════════════════════
  { id: "data_gdpr.export_employee", domain: "data_gdpr", operation: "export_employee", label: "Export employee data (SAR / portability)", lifecycleStages: ["compliance"], autonomy: "execute_with_validation", implementation: "VERIFIED_EXISTING", risk: risk("high", { dataSensitivity: "restricted" }), implementationReferences: [mod("src/lib/pierre/v1/gdpr.ts")], evidence: [ev("route", "src/app/api/pierre/security/export/route.ts", "structured SAR export")] },
  { id: "data_gdpr.export_company", domain: "data_gdpr", operation: "export_company", label: "Export company data (bulk SAR)", lifecycleStages: ["compliance"], autonomy: "execute_with_validation", implementation: "VERIFIED_EXISTING", risk: risk("high", { dataSensitivity: "restricted" }), implementationReferences: [mod("src/lib/pierre/v1/gdpr.ts")], evidence: [ev("route", "src/app/api/pierre/security/export/route.ts", "org-scope export")] },
  { id: "data_gdpr.legal_hold", domain: "data_gdpr", operation: "legal_hold", label: "Set legal hold (blocks anonymization + purge)", lifecycleStages: ["compliance", "archival"], autonomy: "execute_with_validation", implementation: "VERIFIED_EXISTING", risk: risk("high", { reversibility: "partially_reversible" }), implementationReferences: [mod("src/lib/pierre/v1/gdpr.ts")], evidence: [ev("integration_test", "gdpr legal hold", "blocks anonymize/purge")] },
  { id: "data_gdpr.anonymize", domain: "data_gdpr", operation: "anonymize", label: "Anonymize employee (pseudonymization, legal aggregates preserved)", lifecycleStages: ["compliance", "archival"], autonomy: "execute_with_validation", implementation: "VERIFIED_EXISTING", risk: risk("critical", { reversibility: "irreversible", dataSensitivity: "restricted" }), approvals: [{ when: "always", approver: "admin", reason: "irreversible" }], implementationReferences: [mod("src/lib/pierre/v1/gdpr.ts")], evidence: [ev("integration_test", "gdpr anonymize", "pseudonymization + aggregate preservation")] },
  { id: "data_gdpr.purge", domain: "data_gdpr", operation: "purge", label: "Purge employee (physical delete w/ retention guard)", lifecycleStages: ["compliance", "archival"], autonomy: "execute_with_validation", implementation: "VERIFIED_EXISTING", risk: risk("critical", { reversibility: "irreversible", dataSensitivity: "restricted" }), approvals: [{ when: "always", approver: "admin", reason: "irreversible physical delete" }], implementationReferences: [mod("src/lib/pierre/v1/gdpr.ts"), route("src/app/api/pierre/security/purge/route.ts")], evidence: [ev("route", "src/app/api/pierre/security/purge/route.ts", "retention-guarded purge")] },
  { id: "data_gdpr.delete_document", domain: "data_gdpr", operation: "delete_document", label: "Delete a document (erasure)", lifecycleStages: ["compliance"], autonomy: "execute_with_validation", implementation: "VERIFIED_EXISTING", risk: risk("high", { reversibility: "irreversible" }), implementationReferences: [mod("src/lib/pierre/v1/gdpr.ts")], evidence: [ev("integration_test", "gdpr delete document", "erasure path")] },
  { id: "data_gdpr.access_log", domain: "data_gdpr", operation: "access_log", label: "Data access audit trail (who/what/when, no values)", lifecycleStages: ["compliance"], autonomy: "execute_autonomous", implementation: "VERIFIED_EXISTING", risk: risk("medium"), implementationReferences: [mod("src/lib/pierre/v1/gdpr.ts")], evidence: [ev("migration_table", "pierre_rt_data_access_log", "access log")] },
  { id: "data_gdpr.retention", domain: "data_gdpr", operation: "retention", label: "Enforce statutory retention & scheduled deletion", lifecycleStages: ["compliance", "archival", "proactive"], autonomy: "execute_with_validation", implementation: "PARTIAL", risk: risk("high", { legalSensitivity: "high" }), countryRuleDependencies: [{ ruleFamily: "document_retention", required: true }] },
  { id: "data_gdpr.legal_basis", domain: "data_gdpr", operation: "legal_basis", label: "Maintain legal basis & data minimization", lifecycleStages: ["compliance"], autonomy: "prepare_draft", implementation: "LEGAL_CONTENT_REQUIRED", risk: risk("high", { legalSensitivity: "high" }), countryRuleDependencies: [{ ruleFamily: "data_protection", required: true }] },
  { id: "data_gdpr.consent_proof", domain: "data_gdpr", operation: "consent_proof", label: "Maintain consent proof for communications", lifecycleStages: ["compliance", "communications"], autonomy: "execute_autonomous", implementation: "MISSING", risk: risk("high", { legalSensitivity: "high" }), countryRuleDependencies: [{ ruleFamily: "data_protection", required: true }] },
  { id: "data_gdpr.right_to_object", domain: "data_gdpr", operation: "right_to_object", label: "Right to object / opt-out from a processing category", lifecycleStages: ["compliance"], autonomy: "execute_with_validation", implementation: "PARTIAL", risk: risk("high", { legalSensitivity: "high" }) },

  // ══ T. REPORTING & STEERING ════════════════════════════════════════════════
  { id: "reporting.headcount_turnover", domain: "reporting", operation: "headcount_turnover", label: "Headcount & turnover reporting", lifecycleStages: ["reporting"], autonomy: "execute_autonomous", implementation: "PARTIAL", risk: risk("low"), implementationReferences: [mod("src/lib/pierre/v1/cockpit-snapshot.ts")] },
  { id: "reporting.absenteeism", domain: "reporting", operation: "absenteeism", label: "Absenteeism reporting", lifecycleStages: ["reporting"], autonomy: "execute_autonomous", implementation: "MISSING", risk: risk("low") },
  { id: "reporting.recruitment_funnel", domain: "reporting", operation: "recruitment_funnel", label: "Recruitment/onboarding funnel reporting", lifecycleStages: ["reporting"], autonomy: "execute_autonomous", implementation: "MISSING", risk: risk("low") },
  { id: "reporting.completeness_deadlines", domain: "reporting", operation: "completeness_deadlines", label: "Completeness & deadline dashboards", lifecycleStages: ["reporting", "proactive"], autonomy: "execute_autonomous", implementation: "PARTIAL", risk: risk("low"), implementationReferences: [mod("src/lib/pierre/v1/cockpit-snapshot.ts"), mod("src/lib/pierre/v1/completeness.ts")] },
  { id: "reporting.executive_report", domain: "reporting", operation: "executive_report", label: "Executive/HR periodic reports + recommended actions", lifecycleStages: ["reporting"], autonomy: "prepare_draft", implementation: "MISSING", risk: risk("low") },
  { id: "reporting.anomaly_surfacing", domain: "reporting", operation: "anomaly_surfacing", label: "Surface anomalies & risks", lifecycleStages: ["reporting", "proactive"], autonomy: "execute_autonomous", implementation: "PARTIAL", risk: risk("medium") },

  // ══ U. PROACTIVE OPERATIONS ════════════════════════════════════════════════
  { id: "proactive.scheduler", domain: "proactive", operation: "scheduler", label: "Durable proactive scheduler (bounded recurrence, stop conditions)", lifecycleStages: ["proactive"], autonomy: "execute_autonomous", implementation: "VERIFIED_EXISTING", risk: risk("low"), implementationReferences: [mod("src/lib/pierre/v1/runtime-scheduler.ts"), mod("src/lib/pierre/v1/runtime-schedule-rules.ts")], evidence: [ev("integration_test", "hr-continuity.test.ts", "durable follow-up + stop-condition")] },
  { id: "proactive.followup", domain: "proactive", operation: "followup", label: "Follow-up scheduling (durable, bounded)", lifecycleStages: ["proactive"], autonomy: "execute_autonomous", implementation: "VERIFIED_EXISTING", risk: risk("low"), implementationReferences: [mod("src/lib/pierre/v1/runtime-action-handlers.ts")], evidence: [ev("integration_test", "hr-continuity.test.ts", "bounded recurrence")] },
  { id: "proactive.contract_expiry", domain: "proactive", operation: "contract_expiry", label: "Detect contract expiry & prompt", lifecycleStages: ["proactive", "contract"], autonomy: "execute_autonomous", implementation: "CONTRACT_ONLY", risk: risk("medium"), proactiveSignals: [{ key: "contract_expiry", label: "Contract expiring", detection: "expiry", leadTime: "P30D" }] },
  { id: "proactive.end_of_probation", domain: "proactive", operation: "end_of_probation", label: "End-of-probation monitoring", lifecycleStages: ["proactive", "onboarding"], autonomy: "execute_autonomous", implementation: "CONTRACT_ONLY", risk: risk("medium"), proactiveSignals: [{ key: "probation_end", label: "Probation ending", detection: "date_threshold", leadTime: "P14D" }], countryRuleDependencies: [{ ruleFamily: "probation_periods", required: true }] },
  { id: "proactive.missing_document", domain: "proactive", operation: "missing_document", label: "Missing-document detection & chase", lifecycleStages: ["proactive", "onboarding"], autonomy: "execute_autonomous", implementation: "PARTIAL", risk: risk("low"), proactiveSignals: [{ key: "missing_doc", label: "Required document missing", detection: "missing_document" }] },
  { id: "proactive.expiring_training", domain: "proactive", operation: "expiring_training", label: "Expiring training/certification detection", lifecycleStages: ["proactive", "training"], autonomy: "execute_autonomous", implementation: "MISSING", risk: risk("medium"), proactiveSignals: [{ key: "training_expiry", label: "Training expiring", detection: "expiry", leadTime: "P60D" }] },
  { id: "proactive.blocked_signature", domain: "proactive", operation: "blocked_signature", label: "Blocked-signature detection", lifecycleStages: ["proactive", "contract"], autonomy: "execute_autonomous", implementation: "PARTIAL", risk: risk("medium"), proactiveSignals: [{ key: "blocked_signature", label: "Signature stuck", detection: "sla_breach" }] },
  { id: "proactive.payroll_anomaly", domain: "proactive", operation: "payroll_anomaly", label: "Payroll anomaly / untreated absence detection", lifecycleStages: ["proactive", "payroll"], autonomy: "execute_autonomous", implementation: "CONTRACT_ONLY", risk: risk("high") },
  { id: "proactive.retention_deletion", domain: "proactive", operation: "retention_deletion", label: "Retention obligation & scheduled deletion detection", lifecycleStages: ["proactive", "compliance"], autonomy: "execute_with_validation", implementation: "PARTIAL", risk: risk("high", { legalSensitivity: "high" }), countryRuleDependencies: [{ ruleFamily: "document_retention", required: true }] },
  { id: "proactive.sla_breach", domain: "proactive", operation: "sla_breach", label: "SLA breach & provider-chase detection", lifecycleStages: ["proactive"], autonomy: "execute_autonomous", implementation: "PARTIAL", risk: risk("medium"), proactiveSignals: [{ key: "sla_breach", label: "SLA breached", detection: "sla_breach" }] },

  // ══ V. PIERRE ADMINISTRATION ═══════════════════════════════════════════════
  { id: "pierre_admin.autonomy_config", domain: "pierre_admin", operation: "autonomy_config", label: "Company autonomy & permission delegation config", lifecycleStages: ["compliance"], autonomy: "execute_with_validation", implementation: "VERIFIED_EXISTING", risk: risk("high"), implementationReferences: [mod("src/lib/pierre/v1/autonomy.ts")], evidence: [ev("integration_test", "hr-autonomy.test.ts", "autonomy + delegation")] },
  { id: "pierre_admin.approval_workflow", domain: "pierre_admin", operation: "approval_workflow", label: "Human approval workflow (validation requests + fingerprinting)", lifecycleStages: ["compliance"], autonomy: "execute_with_validation", implementation: "VERIFIED_EXISTING", risk: risk("high"), implementationReferences: [mod("src/lib/pierre/v1/runtime-action-handlers.ts")], evidence: [ev("integration_test", "hr-governance.test.ts", "approval fingerprint + stale-consent prevention")] },
  { id: "pierre_admin.action_registry", domain: "pierre_admin", operation: "action_registry", label: "Closed autonomous action registry (fail-closed)", lifecycleStages: ["compliance"], autonomy: "execute_autonomous", implementation: "VERIFIED_EXISTING", risk: risk("high"), implementationReferences: [mod("src/lib/pierre/v1/runtime-action-registry.ts")], evidence: [ev("integration_test", "hr-governance-runtime.test.ts", "closed registry, fail-closed dispatch")] },
  { id: "pierre_admin.cloneguard", domain: "pierre_admin", operation: "cloneguard", label: "CloneGuard approval & prohibition gates", lifecycleStages: ["compliance"], autonomy: "execute_autonomous", implementation: "VERIFIED_EXISTING", risk: risk("high"), implementationReferences: [mod("src/lib/pierre/v1/cloneguard.ts")], evidence: [ev("integration_test", "hr-cloneguard.test.ts / hr-cloneguard-runtime.test.ts", "prohibition + approval gates")] },
  { id: "pierre_admin.mission_orchestration", domain: "pierre_admin", operation: "mission_orchestration", label: "Mission creation & orchestration", lifecycleStages: ["compliance"], autonomy: "execute_autonomous", implementation: "VERIFIED_EXISTING", risk: risk("medium"), implementationReferences: [mod("src/lib/pierre/v1/mission-service.ts")], evidence: [ev("integration_test", "hr-mission-control.test.ts", "mission orchestration")] },
  { id: "pierre_admin.durable_queue", domain: "pierre_admin", operation: "durable_queue", label: "Durable task queue with leasing + fair claim", lifecycleStages: ["compliance"], autonomy: "execute_autonomous", implementation: "VERIFIED_EXISTING", risk: risk("high"), implementationReferences: [mod("src/lib/pierre/v1/queue.ts"), mod("src/lib/pierre/v1/fair-claim.ts")], evidence: [ev("p8_proof", ".p89-proofs/p89-100k-fbb957a4f5", "3174 jobs/s overlap=0 + fair-claim tests")] },
  { id: "pierre_admin.recovery", domain: "pierre_admin", operation: "recovery", label: "Worker lease recovery with fencing", lifecycleStages: ["compliance"], autonomy: "execute_autonomous", implementation: "VERIFIED_EXISTING", risk: risk("high"), implementationReferences: [mod("src/lib/pierre/v1/runtime-lease-controller.ts"), mod("src/lib/pierre/v1/queue.ts")], evidence: [ev("p8_proof", ".p89-proofs/p89-final-2fa5898d89/failures.json", "crash→recover→single completion")] },
  { id: "pierre_admin.audit_trail", domain: "pierre_admin", operation: "audit_trail", label: "Immutable audit trail & observability", lifecycleStages: ["compliance", "reporting"], autonomy: "execute_autonomous", implementation: "VERIFIED_EXISTING", risk: risk("medium"), implementationReferences: [route("src/app/api/pierre/use/audit-trail/route.ts")], evidence: [ev("integration_test", "hr-audit-trail.test.ts / hr-audit-trail-runtime.test.ts", "immutable audit")] },
  { id: "pierre_admin.permission_enforcement", domain: "pierre_admin", operation: "permission_enforcement", label: "API-layer permission enforcement + escalation prevention", lifecycleStages: ["compliance"], autonomy: "execute_autonomous", implementation: "VERIFIED_EXISTING", risk: risk("high"), implementationReferences: [mod("src/lib/pierre/v1/rbac.ts"), mod("src/lib/pierre/v1/membership-invitations.ts")], evidence: [ev("integration_test", "p86-roles-and-ownership.itest.ts", "no privilege escalation")] },
  { id: "pierre_admin.country_config", domain: "pierre_admin", operation: "country_config", label: "Country configuration (jurisdiction resolution + packs)", lifecycleStages: ["compliance"], autonomy: "execute_with_validation", implementation: "PARTIAL", risk: risk("high", { legalSensitivity: "high" }), implementationReferences: [mod("src/lib/pierre/v1/hr-canon/country-packs/index.ts")], countryRuleDependencies: [{ ruleFamily: "collective_agreements", required: false }] },
  { id: "pierre_admin.sending_identity", domain: "pierre_admin", operation: "sending_identity", label: "Sending identity, channels & limits config", lifecycleStages: ["compliance", "communications"], autonomy: "execute_with_validation", implementation: "VERIFIED_EXISTING", risk: risk("medium"), implementationReferences: [mod("src/lib/pierre/v1/communication-provider-config.ts"), mod("src/lib/pierre/v1/runtime-limits.ts")], evidence: [ev("integration_test", "pierre-channels-b33.test.ts", "channel/identity config")] },
];

export const HR_CAPABILITIES: readonly HrCapabilityDefinition[] = RAW.map(defineCapability);
export const HR_CAPABILITY_IDS: readonly string[] = HR_CAPABILITIES.map((c) => c.id);
export function getCapability(id: string): HrCapabilityDefinition | undefined { return HR_CAPABILITIES.find((c) => c.id === id); }
export function capabilitiesByDomain(domain: string): HrCapabilityDefinition[] { return HR_CAPABILITIES.filter((c) => c.domain === domain); }
